// Code generated by Loom, DO NOT EDIT.
//
// Code Generator
//
// Command:
// loom

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	_ "example.com/ticktock/design"
	"github.com/CaliLuke/loom/codegen/generator"
	"github.com/CaliLuke/loom/eval"
	"github.com/CaliLuke/loom/expr"
	loom "github.com/CaliLuke/loom/pkg"
)

func main() {
	var (
		out     = flag.String("output", "", "")
		version = flag.String("version", "", "")
		cmdl    = flag.String("cmd", "", "")
		debug   = flag.Bool("debug", false, "")
		ver     int
	)
	{
		flag.Parse()
		if *out == "" {
			fail("missing output flag")
		}
		if *version == "" {
			fail("missing version flag")
		}
		if *cmdl == "" {
			fail("missing cmd flag")
		}
		v, err := strconv.Atoi(*version)
		if err != nil {
			fail("invalid version %s", *version)
		}
		ver = v
	}

	startBinary := time.Now()
	if *debug {
		debugStage(*debug, "binary-startup", startBinary, "cmd=%s output=%s", *cmdl, *out)
	}

	if ver > loom.Major {
		fail("cannot run loom %s on design using loom v%s\n", loom.Version(), *version)
	}

	startCheckErrors := time.Now()
	if err := eval.Context.Errors; err != nil {
		failStage("eval.Context.Errors", err)
	}
	debugStage(*debug, "eval.Context.Errors", startCheckErrors, "status=ok")

	startRunDSL := time.Now()
	if err := expr.RegisterDefaultRoots(); err != nil {
		failStage("eval.RunDSL", err)
	}
	if err := eval.RunDSL(); err != nil {
		failStage("eval.RunDSL", err)
	}
	debugStage(*debug, "eval.RunDSL", startRunDSL, "status=ok")

	startGenerate := time.Now()
	outputs, err := generator.Generate(*out, "gen", *debug)
	if err != nil {
		failStage("generator.Generate", err)
	}
	debugStage(*debug, "generator.Generate", startGenerate, "outputs=%d", len(outputs))
	debugStage(*debug, "total", startBinary, "outputs=%d", len(outputs))
	fmt.Println(strings.Join(outputs, "\n"))
}

func fail(msg string, vals ...any) {
	fmt.Fprintf(os.Stderr, msg, vals...)
	os.Exit(1)
}

func failStage(stage string, err error) {
	fail("stage %s: %s", stage, err)
}

func debugStage(debug bool, stage string, start time.Time, format string, vals ...any) {
	if !debug {
		return
	}
	msg := ""
	if format != "" {
		msg = " " + fmt.Sprintf(format, vals...)
	}
	fmt.Fprintf(os.Stderr, "[loom-debug] stage=%s duration=%s%s\n", stage, time.Since(start), msg)
}
