package codegen

import (
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"

	loom "github.com/CaliLuke/loom/pkg"
)

type (
	// HeaderData contains the typed data needed to render a generated Go file header.
	HeaderData struct {
		Title   string
		Pkg     string
		Imports []*ImportSpec
		// Scaffold marks a consumer-owned file that Loom generates once and
		// never overwrites. Scaffold headers invite edits instead of carrying
		// the machine-readable "DO NOT EDIT" marker that makes linters and
		// review tooling skip the file.
		Scaffold bool
	}
)

// Header returns a Go source file header section template.
func Header(title, pack string, imports []*ImportSpec) *SectionTemplate {
	return &SectionTemplate{
		Name: "source-header",
		Data: &HeaderData{Title: title, Pkg: pack, Imports: imports},
	}
}

// ScaffoldHeader returns a header section template for consumer-owned scaffold
// files that Loom generates once and never overwrites.
func ScaffoldHeader(title, pack string, imports []*ImportSpec) *SectionTemplate {
	return &SectionTemplate{
		Name: "source-header",
		Data: &HeaderData{Title: title, Pkg: pack, Imports: imports, Scaffold: true},
	}
}

// ManifestFile returns the generation manifest written to gen/loom.json.
func ManifestFile(designDigest string) *File {
	data := struct {
		LoomVersion  string `json:"loom_version"`
		DesignDigest string `json:"design_digest"`
	}{
		LoomVersion:  loom.Version(),
		DesignDigest: designDigest,
	}
	b, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("marshal generation manifest: %s", err))
	}
	return &File{
		Path: filepath.Join(Gendir, "loom.json"),
		Sections: []Section{&SectionTemplate{
			Name:   "loom-manifest",
			Source: string(b),
		}},
	}
}

// AddImport adds imports to a section template that was generated with
// Header.
func AddImport(section *SectionTemplate, imprts ...*ImportSpec) {
	AddSectionImport(section, imprts...)
}

// AddSectionImport adds imports to a generated header section.
func AddSectionImport(section Section, imprts ...*ImportSpec) {
	if len(imprts) == 0 {
		return
	}
	if data := HeaderDataForSection(section); data != nil {
		seen := make(map[ImportSpec]struct{}, len(data.Imports)+len(imprts))
		for _, spec := range data.Imports {
			if spec == nil {
				continue
			}
			seen[*spec] = struct{}{}
		}
		for _, spec := range imprts {
			if spec == nil {
				continue
			}
			if _, ok := seen[*spec]; ok {
				continue
			}
			seen[*spec] = struct{}{}
			data.Imports = append(data.Imports, spec)
		}
	}
}

// AddFileImport adds imports to the first header section of the given file.
func AddFileImport(file *File, imprts ...*ImportSpec) {
	if file == nil {
		return
	}
	AddSectionImport(file.HeaderSection(), imprts...)
}

// HeaderSectionData returns the typed header data if the section is a generated header.
func HeaderSectionData(section *SectionTemplate) *HeaderData {
	return HeaderDataForSection(section)
}

// HeaderDataForSection returns typed header data for a generated header
// section, independent of the concrete Section implementation.
func HeaderDataForSection(section Section) *HeaderData {
	if section == nil {
		return nil
	}
	switch s := section.(type) {
	case *SectionTemplate:
		data, ok := s.Data.(*HeaderData)
		if !ok {
			return nil
		}
		return data
	default:
		return nil
	}
}

func renderHeaderSection(w io.Writer, data *HeaderData) error {
	if data == nil {
		return nil
	}
	if data.Title != "" {
		marker := "// Code generated by Loom, DO NOT EDIT.\n//\n"
		if data.Scaffold {
			marker = "// Generated once by Loom. Edit freely; regeneration never overwrites this file.\n//\n"
		}
		if _, err := fmt.Fprint(w, marker); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "%s\n//\n// Command:\n%s\n\n", Comment(data.Title), Comment(CommandLine())); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "package %s\n\n", data.Pkg); err != nil {
		return err
	}
	if len(data.Imports) == 0 {
		return nil
	}
	if len(data.Imports) == 1 {
		_, err := fmt.Fprintf(w, "import \t%s\n\n", data.Imports[0].Code())
		return err
	}
	if _, err := fmt.Fprintln(w, "import ("); err != nil {
		return err
	}
	for _, imp := range data.Imports {
		if _, err := fmt.Fprintf(w, "\t%s\n", imp.Code()); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(w, ")"); err != nil {
		return err
	}
	_, err := fmt.Fprintln(w)
	return err
}
