package codegen

import (
	"slices"
	"sync"

	"github.com/CaliLuke/loom/eval"
)

type (
	// GenerateFunc makes it possible to modify the files generated by the
	// Loom code generators and other plugins. A GenerateFunc accepts the Go
	// import path of the "gen" package, the design roots as well as the
	// currently generated files (produced initially by the Loom generators
	// and potentially modified by previously run plugins) and returns a new
	// set of files.
	GenerateFunc func(genpkg string, roots []eval.Root, files []*File) ([]*File, error)

	// PrepareFunc makes it possible to modify the design roots before
	// the files being generated by the Loom code generators or other plugins.
	PrepareFunc func(genpkg string, roots []eval.Root) error

	// plugin is a plugin that has been registered with a given command.
	plugin struct {
		// PrepareFunc is the plugin preparation function.
		PrepareFunc
		// GenerateFunc is the plugin generator function.
		GenerateFunc
		// name is the plugin name.
		name string
		// cmd is the name of cmd to run.
		cmd string
		// if first is set the plugin cmd must run before all other plugins.
		first bool
		// if last is set the plugin cmd must run after all other plugins.
		last bool
	}

	// Registry stores registered plugins in execution order.
	Registry struct {
		mu      sync.RWMutex
		plugins []*plugin
	}
)

var defaultRegistry = NewRegistry()

// NewRegistry creates an empty plugin registry.
func NewRegistry() *Registry {
	return &Registry{}
}

// Snapshot returns a stable copy of the registry contents suitable for one
// generation run.
func (r *Registry) Snapshot() *Registry {
	r.mu.RLock()
	defer r.mu.RUnlock()
	plugins := append([]*plugin(nil), r.plugins...)
	return &Registry{plugins: plugins}
}

// RegisterPlugin adds the plugin to the list of plugins to be invoked with the
// given command.
func RegisterPlugin(name string, cmd string, pre PrepareFunc, p GenerateFunc) {
	defaultRegistry.RegisterPlugin(name, cmd, pre, p)
}

// RegisterPlugin adds the plugin to the registry.
func (r *Registry) RegisterPlugin(name string, cmd string, pre PrepareFunc, p GenerateFunc) {
	np := &plugin{name: name, PrepareFunc: pre, GenerateFunc: p, cmd: cmd}
	r.mu.Lock()
	defer r.mu.Unlock()
	r.plugins = insertPlugin(r.plugins, np)
}

func insertPlugin(plugins []*plugin, np *plugin) []*plugin {
	var inserted bool
	for i, plgn := range plugins {
		if plgn.last || (!plgn.first && np.name < plgn.name) {
			plugins = append(plugins[:i], append([]*plugin{np}, plugins[i:]...)...) //nolint:gocritic
			inserted = true
			break
		}
	}
	if !inserted {
		plugins = append(plugins, np)
	}
	return plugins
}

// RegisterPluginFirst adds the plugin to the beginning of the list of plugins
// to be invoked with the given command. If more than one plugins are registered
// using this, the plugins will be sorted alphabetically by their names. If two
// plugins have same names, then they are sorted by registration order.
func RegisterPluginFirst(name string, cmd string, pre PrepareFunc, p GenerateFunc) {
	defaultRegistry.RegisterPluginFirst(name, cmd, pre, p)
}

// RegisterPluginFirst adds the plugin to the beginning of the registry.
func (r *Registry) RegisterPluginFirst(name string, cmd string, pre PrepareFunc, p GenerateFunc) {
	np := &plugin{name: name, PrepareFunc: pre, GenerateFunc: p, cmd: cmd, first: true}
	r.mu.Lock()
	defer r.mu.Unlock()
	var inserted bool
	for i, plgn := range r.plugins {
		if !plgn.first || np.name < plgn.name {
			r.plugins = append(r.plugins[:i], append([]*plugin{np}, r.plugins[i:]...)...) //nolint:gocritic
			inserted = true
			break
		}
	}
	if !inserted {
		r.plugins = append(r.plugins, np)
	}
}

// RegisterPluginLast adds the plugin to the end of the list of plugins
// to be invoked with the given command. If more than one plugins are registered
// using this, the plugins will be sorted alphabetically by their names. If two
// plugins have same names, then they are sorted by registration order.
func RegisterPluginLast(name string, cmd string, pre PrepareFunc, p GenerateFunc) {
	defaultRegistry.RegisterPluginLast(name, cmd, pre, p)
}

// RegisterPluginLast adds the plugin to the end of the registry.
func (r *Registry) RegisterPluginLast(name string, cmd string, pre PrepareFunc, p GenerateFunc) {
	np := &plugin{name: name, PrepareFunc: pre, GenerateFunc: p, cmd: cmd, last: true}
	r.mu.Lock()
	defer r.mu.Unlock()
	var inserted bool
	for i, plgn := range slices.Backward(r.plugins) {
		if !plgn.last || plgn.name < np.name {
			r.plugins = append(r.plugins[:i+1], append([]*plugin{np}, r.plugins[i+1:]...)...) //nolint:gocritic
			inserted = true
			break
		}
	}
	if !inserted {
		r.plugins = append(r.plugins, np)
	}
}

// RunPluginsPrepare executes the plugins prepare functions in the order
// they were registered.
func RunPluginsPrepare(cmd, genpkg string, roots []eval.Root) error {
	return defaultRegistry.RunPluginsPrepare(cmd, genpkg, roots)
}

// RunPluginsPrepare executes the plugins prepare functions in the order they
// were registered.
func (r *Registry) RunPluginsPrepare(cmd, genpkg string, roots []eval.Root) error {
	r.mu.RLock()
	defer r.mu.RUnlock()
	for _, plugin := range r.plugins {
		if plugin.cmd != cmd {
			continue
		}
		if plugin.PrepareFunc != nil {
			err := plugin.PrepareFunc(genpkg, roots)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// RunPlugins executes the plugins registered with the given command in the order
// they were registered.
func RunPlugins(cmd, genpkg string, roots []eval.Root, genfiles []*File) ([]*File, error) {
	return defaultRegistry.RunPlugins(cmd, genpkg, roots, genfiles)
}

// RunPlugins executes the plugins registered with the given command in the
// order they were registered.
func (r *Registry) RunPlugins(cmd, genpkg string, roots []eval.Root, genfiles []*File) ([]*File, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	for _, plugin := range r.plugins {
		if plugin.cmd != cmd {
			continue
		}
		gs, err := plugin.GenerateFunc(genpkg, roots, genfiles)
		if err != nil {
			return nil, err
		}
		genfiles = gs
	}
	return genfiles, nil
}

// DefaultRegistrySnapshot returns a stable copy of the package-level plugin
// registry for a single generation run.
func DefaultRegistrySnapshot() *Registry {
	return defaultRegistry.Snapshot()
}
