package vet

import (
	"bytes"
	"path/filepath"
	"testing"

	"github.com/CaliLuke/loom/expr"
	"github.com/stretchr/testify/require"
)

func TestAnalyzeConfiguredHTTPServiceMounts(t *testing.T) {
	moduleRoot := t.TempDir()
	writeTestFile(t, filepath.Join(moduleRoot, "go.mod"), "module example.com/service\n\ngo 1.27.0\n")
	writeGeneratedServerStub(t, moduleRoot, "widgets")
	writeGeneratedServerStub(t, moduleRoot, "reports")
	writeTestFile(t, filepath.Join(moduleRoot, "cmd", "api", "main.go"), `package main

import widgetsserver "example.com/service/gen/http/widgets/server"

func main() {
	server := new(widgetsserver.Server)
	if enabled() {
		widgetsserver.Mount(nil, server)
	}
}

func enabled() bool {
	return true
}
`)
	writeTestFile(t, filepath.Join(moduleRoot, "cmd", "worker", "main.go"), `package main

import reportsserver "example.com/service/gen/http/reports/server"

func main() {
	server := new(reportsserver.Server)
	server.Mount(nil)
}
`)

	t.Run("library modules omit the rule", func(t *testing.T) {
		diagnostics, err := analyzeConfiguredHTTPMounts(moduleRoot, mountedServicesDesign())

		require.NoError(t, err)
		require.Empty(t, diagnostics)
	})

	t.Run("conditional direct mount counts", func(t *testing.T) {
		design := mountedServicesDesign()
		design.API.Meta = expr.MetaExpr{httpEntrypointMeta: {"./cmd/api"}}

		diagnostics, err := analyzeConfiguredHTTPMounts(moduleRoot, design)

		require.NoError(t, err)
		require.Equal(t, []string{RuleServiceNotMounted + ":service.reports.http"}, diagnosticKeys(diagnostics))
		require.Contains(t, diagnostics[0].Message, `HTTP service "reports"`)
		for _, format := range []Format{FormatText, FormatJSON, FormatSARIF} {
			var output bytes.Buffer
			require.NoError(t, WriteReport(&output, Report{Diagnostics: diagnostics}, format))
			require.Contains(t, output.String(), RuleServiceNotMounted)
		}
	})

	t.Run("multiple entrypoints and method mount count", func(t *testing.T) {
		design := mountedServicesDesign()
		design.API.Meta = expr.MetaExpr{httpEntrypointMeta: {"./cmd/api", "./cmd/worker"}}

		diagnostics, err := analyzeConfiguredHTTPMounts(moduleRoot, design)

		require.NoError(t, err)
		require.Empty(t, diagnostics)
	})

	t.Run("service suppression", func(t *testing.T) {
		design := mountedServicesDesign()
		design.API.Meta = expr.MetaExpr{httpEntrypointMeta: {"./cmd/api"}}
		design.API.HTTP.Services[1].ServiceExpr.Meta = expr.MetaExpr{SuppressionMeta: {RuleServiceNotMounted}}

		diagnostics, err := analyzeConfiguredHTTPMounts(moduleRoot, design)

		require.NoError(t, err)
		require.Empty(t, diagnostics)
	})

	t.Run("invalid entrypoint fails instead of reporting every service", func(t *testing.T) {
		design := mountedServicesDesign()
		design.API.Meta = expr.MetaExpr{httpEntrypointMeta: {"./cmd/missing"}}

		diagnostics, err := analyzeConfiguredHTTPMounts(moduleRoot, design)

		require.ErrorContains(t, err, "load configured HTTP mount entrypoint")
		require.Empty(t, diagnostics)
	})
}

func mountedServicesDesign() *expr.RootExpr {
	httpRoot := &expr.HTTPExpr{}
	for _, name := range []string{"widgets", "reports"} {
		service := &expr.ServiceExpr{Name: name}
		httpRoot.Services = append(httpRoot.Services, &expr.HTTPServiceExpr{
			Root:          httpRoot,
			ServiceExpr:   service,
			HTTPEndpoints: []*expr.HTTPEndpointExpr{{MethodExpr: &expr.MethodExpr{Name: "show", Service: service}}},
		})
	}
	return &expr.RootExpr{API: &expr.APIExpr{HTTP: httpRoot}}
}

func writeGeneratedServerStub(t *testing.T, moduleRoot, service string) {
	t.Helper()
	writeTestFile(t, filepath.Join(moduleRoot, "gen", "http", service, "server", "server.go"), `// Code generated by Loom, DO NOT EDIT.
package server

type Server struct {
}

func Mount(_ any, _ *Server) {
}

func (s *Server) Mount(mux any) {
	Mount(mux, s)
}
`)
}
