package vet

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"golang.org/x/mod/modfile"
)

const loomHTTPImportPath = "github.com/CaliLuke/loom/http"

func analyzeModule(dir string) ([]Diagnostic, error) {
	root, err := findModuleRoot(dir)
	if err != nil {
		return nil, err
	}
	routes, err := analyzeRoutes(root)
	if err != nil {
		return nil, err
	}
	versions, err := analyzeGeneratedVersions(root)
	if err != nil {
		return nil, err
	}
	return append(routes, versions...), nil
}

func findModuleRoot(dir string) (string, error) {
	current, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("resolve module directory: %w", err)
	}
	for {
		info, statErr := os.Stat(filepath.Join(current, "go.mod"))
		switch {
		case statErr == nil && info.Mode().IsRegular():
			return current, nil
		case statErr == nil:
			return "", fmt.Errorf("module file %s is not a regular file", filepath.Join(current, "go.mod"))
		case !os.IsNotExist(statErr):
			return "", fmt.Errorf("inspect module directory: %w", statErr)
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", fmt.Errorf("no go.mod found from %s", dir)
		}
		current = parent
	}
}

func analyzeRoutes(root string) ([]Diagnostic, error) {
	var diagnostics []Diagnostic
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != root && skipDirectory(entry.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".go" || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		fileDiagnostics, err := analyzeRouteFile(root, path)
		if err != nil {
			return err
		}
		diagnostics = append(diagnostics, fileDiagnostics...)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("analyze Loom mux routes: %w", err)
	}
	return diagnostics, nil
}

func skipDirectory(name string) bool {
	switch name {
	case ".git", ".hg", ".svn", "node_modules", "vendor":
		return true
	default:
		return strings.HasPrefix(name, ".")
	}
}

func analyzeRouteFile(root, path string) ([]Diagnostic, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if generatedByLoom(source) {
		return nil, nil
	}
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, path, source, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	loomAliases := loomHTTPAliases(file)
	if len(loomAliases) == 0 {
		return nil, nil
	}

	globalMuxes := make(map[string]struct{})
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		collectMuxValueSpecs(general.Specs, loomAliases, globalMuxes)
	}

	var diagnostics []Diagnostic
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Body == nil {
			continue
		}
		muxes := cloneSet(globalMuxes)
		collectMuxParameters(function.Type.Params, loomAliases, muxes)
		ast.Inspect(function.Body, func(node ast.Node) bool {
			switch actual := node.(type) {
			case *ast.AssignStmt:
				collectMuxAssignments(actual, loomAliases, muxes)
			case *ast.DeclStmt:
				if declaration, ok := actual.Decl.(*ast.GenDecl); ok {
					collectMuxValueSpecs(declaration.Specs, loomAliases, muxes)
				}
			case *ast.CallExpr:
				if !isMuxHandleCall(actual, loomAliases, muxes) || sourceSuppressed(fileSet, file, actual, RuleRouteOutsideDesign) {
					return true
				}
				position := fileSet.Position(actual.Pos())
				relative, relErr := filepath.Rel(root, path)
				if relErr != nil {
					relative = path
				}
				diagnostics = append(diagnostics, Diagnostic{
					Rule:     RuleRouteOutsideDesign,
					Severity: SeverityError,
					Message:  unmanagedRouteMessage(actual),
					Location: Location{Path: filepath.ToSlash(relative), Line: position.Line, Column: position.Column},
				})
			}
			return true
		})
	}
	return diagnostics, nil
}

func generatedByLoom(source []byte) bool {
	prefix := source
	if len(prefix) > 512 {
		prefix = prefix[:512]
	}
	return strings.Contains(string(prefix), "Code generated by Loom, DO NOT EDIT.")
}

func loomHTTPAliases(file *ast.File) map[string]struct{} {
	aliases := make(map[string]struct{})
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil || path != loomHTTPImportPath {
			continue
		}
		alias := "http"
		if spec.Name != nil {
			alias = spec.Name.Name
		}
		if alias != "." && alias != "_" {
			aliases[alias] = struct{}{}
		}
	}
	return aliases
}

func collectMuxParameters(fields *ast.FieldList, aliases, muxes map[string]struct{}) {
	if fields == nil {
		return
	}
	for _, field := range fields.List {
		if !isMuxType(field.Type, aliases) {
			continue
		}
		for _, name := range field.Names {
			muxes[name.Name] = struct{}{}
		}
	}
}

func isMuxType(node ast.Expr, aliases map[string]struct{}) bool {
	selector, ok := node.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	identifier, ok := selector.X.(*ast.Ident)
	if !ok {
		return false
	}
	if _, ok := aliases[identifier.Name]; !ok {
		return false
	}
	switch selector.Sel.Name {
	case "Muxer", "MiddlewareMuxer", "ResolverMuxer":
		return true
	default:
		return false
	}
}

func collectMuxAssignments(assignment *ast.AssignStmt, aliases, muxes map[string]struct{}) {
	for index, right := range assignment.Rhs {
		if index >= len(assignment.Lhs) || !isMuxValue(right, aliases, muxes) {
			continue
		}
		if identifier, ok := assignment.Lhs[index].(*ast.Ident); ok {
			muxes[identifier.Name] = struct{}{}
		}
	}
}

func collectMuxValueSpecs(specs []ast.Spec, aliases, muxes map[string]struct{}) {
	for _, rawSpec := range specs {
		spec, ok := rawSpec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		for index, value := range spec.Values {
			if index >= len(spec.Names) || !isMuxValue(value, aliases, muxes) {
				continue
			}
			muxes[spec.Names[index].Name] = struct{}{}
		}
	}
}

func isMuxValue(node ast.Expr, aliases, muxes map[string]struct{}) bool {
	switch actual := node.(type) {
	case *ast.Ident:
		_, ok := muxes[actual.Name]
		return ok
	case *ast.CallExpr:
		selector, ok := actual.Fun.(*ast.SelectorExpr)
		if !ok || selector.Sel.Name != "NewMuxer" {
			return false
		}
		identifier, ok := selector.X.(*ast.Ident)
		if !ok {
			return false
		}
		_, ok = aliases[identifier.Name]
		return ok
	default:
		return false
	}
}

func isMuxHandleCall(call *ast.CallExpr, aliases, muxes map[string]struct{}) bool {
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != "Handle" {
		return false
	}
	return isMuxValue(selector.X, aliases, muxes)
}

func unmanagedRouteMessage(call *ast.CallExpr) string {
	method := stringLiteralArgument(call, 0)
	path := stringLiteralArgument(call, 1)
	switch {
	case method != "" && path != "":
		return fmt.Sprintf("route %s %s is registered directly on a Loom mux; declare and mount it through the design", method, path)
	case path != "":
		return fmt.Sprintf("route %s is registered directly on a Loom mux; declare and mount it through the design", path)
	default:
		return "route is registered directly on a Loom mux; declare and mount it through the design"
	}
}

func stringLiteralArgument(call *ast.CallExpr, index int) string {
	if index >= len(call.Args) {
		return ""
	}
	literal, ok := call.Args[index].(*ast.BasicLit)
	if !ok || literal.Kind != token.STRING {
		return ""
	}
	value, err := strconv.Unquote(literal.Value)
	if err != nil {
		return ""
	}
	return value
}

func sourceSuppressed(fileSet *token.FileSet, file *ast.File, node ast.Node, rule string) bool {
	line := fileSet.Position(node.Pos()).Line
	for _, comments := range file.Comments {
		endLine := fileSet.Position(comments.End()).Line
		if endLine != line && endLine != line-1 {
			continue
		}
		for _, comment := range comments.List {
			text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
			if strings.Contains(text, "loom:vet ignore "+rule) || strings.Contains(text, "loom:vet ignore all") {
				return true
			}
		}
	}
	return false
}

func cloneSet(source map[string]struct{}) map[string]struct{} {
	clone := make(map[string]struct{}, len(source))
	for key := range source {
		clone[key] = struct{}{}
	}
	return clone
}

func analyzeGeneratedVersions(root string) ([]Diagnostic, error) {
	moduleData, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, fmt.Errorf("read go.mod: %w", err)
	}
	module, err := modfile.Parse("go.mod", moduleData, nil)
	if err != nil {
		return nil, fmt.Errorf("parse go.mod: %w", err)
	}
	requiredVersion, comparable := effectiveLoomVersion(module)
	if !comparable {
		return nil, nil
	}

	var diagnostics []Diagnostic
	err = filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != root && skipDirectory(entry.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Name() != "loom.json" {
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		manifest := struct {
			Version string `json:"loom_version"`
		}{}
		if unmarshalErr := json.Unmarshal(data, &manifest); unmarshalErr != nil {
			return fmt.Errorf("parse %s: %w", path, unmarshalErr)
		}
		if manifest.Version == "" || manifest.Version == requiredVersion {
			return nil
		}
		relative, relErr := filepath.Rel(root, path)
		if relErr != nil {
			relative = path
		}
		diagnostics = append(diagnostics, Diagnostic{
			Rule:     RuleGeneratedVersionSkew,
			Severity: SeverityError,
			Message:  fmt.Sprintf("generated with Loom %s but go.mod requires %s; run loom gen", manifest.Version, requiredVersion),
			Location: Location{Path: filepath.ToSlash(relative)},
		})
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("inspect generated Loom versions: %w", err)
	}
	return diagnostics, nil
}

func effectiveLoomVersion(module *modfile.File) (string, bool) {
	for _, replacement := range module.Replace {
		if replacement.Old.Path != "github.com/CaliLuke/loom" {
			continue
		}
		if replacement.New.Version == "" {
			return "", false
		}
		return replacement.New.Version, true
	}
	for _, requirement := range module.Require {
		if requirement.Mod.Path == "github.com/CaliLuke/loom" {
			return requirement.Mod.Version, requirement.Mod.Version != ""
		}
	}
	return "", false
}
