package codegen

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/CaliLuke/loom/codegen"
	"github.com/CaliLuke/loom/grpc/codegen/testdata"
)

func TestAnyProtoConstructorsPropagateConversionErrors(t *testing.T) {
	root := RunGRPCDSL(t, testdata.AnyErrorDSL)
	services := CreateGRPCServices(root)

	files := ClientTypeFiles("", services)
	require.Len(t, files, 1)
	var generated bytes.Buffer
	for _, section := range files[0].AllSections()[1:] {
		require.NoError(t, section.Write(&generated))
	}
	code := codegen.FormatTestCode(t, "package client\n"+generated.String())
	require.Contains(t, code, "transformErr := new(error)")
	require.Contains(t, code, "loomgrpc.NewProtoValue")
	require.Contains(t, code, "return zero, *transformErr")
	require.Contains(t, code, "return message, nil")
}

func TestAnyProtoEncodersReturnConstructorErrors(t *testing.T) {
	root := RunGRPCDSL(t, testdata.AnyErrorDSL)
	services := CreateGRPCServices(root)

	requestCode := codegen.SectionsCode(t, ClientFiles("", services)[1].Section("request-encoder"))
	require.Contains(t, requestCode, "return NewProtoConvertRequest(payload)")
	require.NotContains(t, requestCode, "return NewProtoConvertRequest(payload), nil")

	responseCode := codegen.SectionsCode(t, ServerFiles("", services)[1].Section("response-encoder"))
	require.Contains(t, responseCode, "resp, err :=")
	require.Contains(t, responseCode, "if err != nil")
	require.Contains(t, responseCode, "return nil, err")
}
