//nolint:errcheck // Generator helpers write only to in-memory buffers/builders.
package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/CaliLuke/loom/codegen"
	"github.com/CaliLuke/loom/expr"
	"github.com/CaliLuke/loom/internal/transformassign"
)

type transformAttrs struct {
	*codegen.TransformAttrs
	// proto if true indicates that the transformation code is used to initialize
	// a protocol buffer type from a service type. If false, the transformation
	// code is used to initialize a service type from a protocol buffer type.
	proto bool
	// targetInit is the initialization code for the target type for nested
	// map and array types.
	targetInit string
	// wrapped indicates whether the source or target is in a wrapped state.
	// See grpc/docs/FAQ.md. `wrapped` is true and `proto` is true indicates
	// the target attribute is in wrapped state. `wrapped` is true and `proto`
	// is false indicates the source attribute is in wrapped state.
	wrapped bool
	// message is the reference to the Go type generated by protoc for the
	// source message when proto is false.  (protoc builds union struct type
	// names from the parent message name).
	message string
	// errorAware indicates that protobuf conversion can fail at runtime.
	errorAware bool
}

// unionData is used by both transformUnion methods.
type unionData struct {
	Source              *expr.Union
	Target              *expr.Union
	SourceValues        []*expr.NamedAttributeExpr
	TargetValues        []*expr.NamedAttributeExpr
	SourceValueTypeRefs []string
	// TargetWrapperRefs holds wrapper type refs used when assigning from
	// protobuf to Go union (proto -> Go). Empty string means no wrapper.
	TargetWrapperRefs []string
}

// protoBufTransform produces Go code to initialize a data structure defined
// by target from an instance of data structure defined by source. The source
// or target is a protocol buffer type.
//
// source, target are the source and target attributes used in transformation
//
// sourceVar, targetVar are the source and target variables
//
// sourceCtx, targetCtx are the source and target attribute contexts
//
// `proto` param if true indicates that the target is a protocol buffer type
//
// newVar if true initializes a target variable with the generated Go code
// using `:=` operator. If false, it assigns Go code to the target variable
// using `=`.
func protoBufTransform(source, target *expr.AttributeExpr, sourceVar, targetVar string, sourceCtx, targetCtx *codegen.AttributeContext, proto, newVar bool) (string, []*codegen.TransformFunctionData, error) {
	ta := &transformAttrs{TransformAttrs: &codegen.TransformAttrs{
		SourceCtx: sourceCtx,
		TargetCtx: targetCtx,
	}}
	ta.errorAware = proto && containsAny(source)
	if proto {
		target = expr.DupAtt(target)
		removeMeta(target)
		ta.Prefix = "svc"
		ta.proto = true
	} else {
		source = expr.DupAtt(source)
		removeMeta(source)
		ta.Prefix = "protobuf"
		ta.proto = false
	}

	code, err := transformAttribute(source, target, sourceVar, targetVar, newVar, ta)
	if err != nil {
		return "", nil, err
	}

	funcs, err := transformAttributeHelpers(source, target, ta, make(map[string]*codegen.TransformFunctionData))
	if err != nil {
		return "", nil, err
	}

	return strings.TrimRight(code, "\n"), funcs, nil
}

func containsAny(attribute *expr.AttributeExpr) bool {
	found := false
	_ = codegen.Walk(attribute, func(current *expr.AttributeExpr) error {
		if current.Type.Kind() == expr.AnyKind {
			found = true
		}
		return nil
	})
	return found
}

// removeMeta removes meta attributes from the given attribute that cannot be
// honored. This is needed to make sure that any field name overridding is
// removed when generating protobuf types (as protogen itself won't honor these
// overrides).
func removeMeta(att *expr.AttributeExpr) {
	_ = codegen.Walk(att, func(a *expr.AttributeExpr) error {
		delete(a.Meta, "struct:field:name")
		delete(a.Meta, "struct:field:external")
		delete(a.Meta, "struct.field.external") // Deprecated syntax. Only present for backward compatibility.
		return nil
	})
}

// transformAttribute returns the code to initialize a target data structure
// from an instance of source data structure. It returns an error if source and
// target are not compatible for transformation (different types, fields of
// different type).
func transformAttribute(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, error) {
	var (
		initCode string
		err      error
	)

	if err := codegen.IsCompatible(source.Type, target.Type, sourceVar, targetVar); err != nil {
		if ta.proto {
			name := ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
			initCode += renderJenLine(exprCode(targetVar).Op(":=").Op("&").Id(name).Values())
			targetVar += ".Field"
			newVar = false
			target = unwrapAttr(expr.DupAtt(target))
		} else {
			source = unwrapAttr(expr.DupAtt(source))
			sourceVar += ".Field"
		}
		if err = codegen.IsCompatible(source.Type, target.Type, sourceVar, targetVar); err != nil {
			return "", err
		}
	}

	if ta.proto {
		if isUnionMessage(target) {
			ta = dupTransformAttrs(ta)
			ta.message = ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), false, false)
		}
	} else {
		if isUnionMessage(source) {
			ta = dupTransformAttrs(ta)
			ta.message = ta.SourceCtx.Scope.Ref(source, ta.SourceCtx.Pkg(source))
		}
	}

	code, err := transformAttributeByKind(source, target, sourceVar, targetVar, newVar, ta)
	if err != nil {
		return "", err
	}
	// Ensure code ends with newline for proper formatting when used in templates
	if code != "" && !strings.HasSuffix(code, "\n") {
		code += "\n"
	}
	return initCode + code, nil
}

func transformAttributeByKind(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, error) {
	switch {
	case expr.IsArray(source.Type):
		// Top-level array transforms never assign into a pointer field.
		return transformArray(expr.AsArray(source.Type), expr.AsArray(target.Type), sourceVar, targetVar, newVar, false, false, ta)
	case expr.IsMap(source.Type):
		return transformMap(expr.AsMap(source.Type), expr.AsMap(target.Type), sourceVar, targetVar, newVar, false, ta)
	case expr.IsObject(source.Type):
		return transformObject(source, target, sourceVar, targetVar, newVar, ta)
	case expr.IsUnion(source.Type):
		if ta.proto {
			// At top-level we do not expect pointer-to-interface unions.
			return transformUnionToProto(source, target, sourceVar, targetVar, false, ta)
		}
		return transformUnionFromProto(source, target, sourceVar, targetVar, ta)
	case source.Type.Kind() == expr.AnyKind || target.Type.Kind() == expr.AnyKind:
		return transformScalarAssignment(source, target, sourceVar, targetVar, newVar, ta), nil
	default:
		return transformScalarAssignment(source, target, sourceVar, targetVar, newVar, ta), nil
	}
}

func transformScalarAssignment(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) string {
	assign := "="
	if newVar {
		assign = ":="
	}
	srcField := convertType(source, target, false, false, sourceVar, ta)
	return renderJenLine(exprCode(targetVar).Op(assign).Add(exprCode(srcField)))
}

// transformObject returns the code to transform source attribute of object
// type to target attribute of object type. It returns an error if source
// and target are not compatible for transformation.
func transformObject(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, error) {
	initCode, postInitCode := buildPrimitiveObjectInit(source, target, sourceVar, targetVar, ta)

	buffer := &bytes.Buffer{}
	deref := "&"
	// if the target is a raw struct no need to return a pointer
	if _, ok := target.Type.(*expr.Object); ok {
		deref = ""
	}
	assign := "="
	if newVar {
		assign = ":="
	}
	tname := ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
	fmt.Fprintf(buffer, "%s %s %s%s{%s}\n", targetVar, assign, deref, tname, initCode)
	fmt.Fprint(buffer, postInitCode)

	var err error
	walkMatches(source, target, func(srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string) {
		code, fieldErr := buildObjectFieldTransform(sourceVar, targetVar, srcMatt, tgtMatt, srcc, tgtc, n, ta)
		if fieldErr != nil {
			err = fieldErr
			return
		}
		fmt.Fprint(buffer, code)
	})
	if err != nil {
		return "", err
	}

	return buffer.String(), nil
}

func buildPrimitiveObjectInit(source, target *expr.AttributeExpr, sourceVar, targetVar string, ta *transformAttrs) (string, string) {
	var (
		initCode     string
		postInitCode string
	)
	walkMatches(source, target, func(srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string) {
		if !expr.IsPrimitive(srcc.Type) {
			return
		}
		srcField := sourceVar + "." + ta.SourceCtx.Scope.Field(srcc, srcMatt.ElemName(n), true)
		tgtField := ta.TargetCtx.Scope.Field(tgtc, tgtMatt.ElemName(n), true)
		if presenceCode, handled := transformAnyPresenceObjectField(srcField, targetVar+"."+tgtField, srcc, tgtc, ta); handled {
			postInitCode += presenceCode
			return
		}
		srcPtr := ta.SourceCtx.IsPrimitivePointer(n, srcMatt.AttributeExpr)
		tgtPtr := ta.TargetCtx.IsPrimitivePointer(n, tgtMatt.AttributeExpr)
		srcFieldConv := convertType(srcc, tgtc, srcPtr, tgtPtr, srcField, ta)
		exp, updatedPostInit, handled := transformObjectPrimitivePointerCases(
			srcMatt, srcc, tgtc, srcField, tgtField, srcFieldConv, srcPtr, tgtPtr, targetVar, postInitCode, tgtMatt.ElemName(n), n, ta,
		)
		postInitCode = updatedPostInit
		if handled {
			return
		}
		initCode += "\n" + tgtField + ": " + exp + ","
	})
	if initCode != "" {
		initCode += "\n"
	}
	return initCode, postInitCode
}

func transformAnyPresenceObjectField(srcField, tgtField string, source, target *expr.AttributeExpr, ta *transformAttrs) (string, bool) {
	sourceBase := unAlias(source)
	targetBase := unAlias(target)
	if sourceBase.Type.Kind() != expr.AnyKind || targetBase.Type.Kind() != expr.AnyKind {
		return "", false
	}
	if ta.proto {
		converted := convertPrimitiveToProto(sourceBase, targetBase, false, false, "actual", ta)
		return "if " + srcField + ".IsNull() {\n\t" + tgtField + " = structpb.NewNullValue()\n" +
			"} else if actual, ok := " + srcField + ".Value(); ok {\n\t" + tgtField + " = " + converted + "\n}\n", true
	}
	converted := srcField + ".AsInterface()"
	if target.Type.Kind() != expr.AnyKind {
		converted = ta.TargetCtx.Scope.Ref(target, ta.TargetCtx.Pkg(target)) + "(" + converted + ")"
	}
	return "if " + srcField + " != nil {\n\tif _, isNull := " + srcField + ".GetKind().(*structpb.Value_NullValue); isNull {\n\t\t" +
		tgtField + ".SetNull()\n\t} else {\n\t\t" + tgtField + ".SetValue(" + converted + ")\n\t}\n}\n", true
}

func buildObjectFieldTransform(sourceVar, targetVar string, srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string, ta *transformAttrs) (string, error) {
	srcc = unAlias(srcc)
	tgtc = unAlias(tgtc)
	srcValue := sourceVar + "." + ta.SourceCtx.Scope.Field(srcc, srcMatt.ElemName(n), true)
	tgtValue := targetVar + "." + ta.TargetCtx.Scope.Field(tgtc, tgtMatt.ElemName(n), true)
	compatibleSource, compatibleTarget, err := compatibleTransformAttrs(srcc, tgtc, ta)
	if err != nil {
		return "", err
	}
	code, err := objectFieldAssignment(srcValue, tgtValue, compatibleSource, compatibleTarget, ta)
	if err != nil {
		return "", err
	}
	code = wrapObjectFieldNilCheck(code, srcValue, srcMatt, compatibleSource, n, ta)
	return applyObjectFieldDefaults(code, srcValue, tgtValue, srcMatt, tgtMatt, compatibleSource, compatibleTarget, n, ta), nil
}

func compatibleTransformAttrs(srcc, tgtc *expr.AttributeExpr, ta *transformAttrs) (*expr.AttributeExpr, *expr.AttributeExpr, error) {
	if err := codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err == nil {
		return srcc, tgtc, nil
	}
	if ta.proto {
		ta.targetInit = ta.TargetCtx.Scope.Name(tgtc, ta.TargetCtx.Pkg(tgtc), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
		tgtc = unwrapAttr(tgtc)
	} else {
		srcc = unwrapAttr(srcc)
	}
	ta.wrapped = true
	if err := codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err != nil {
		return nil, nil, err
	}
	return srcc, tgtc, nil
}

func objectFieldAssignment(srcVar, tgtVar string, srcc, tgtc *expr.AttributeExpr, ta *transformAttrs) (string, error) {
	_, isUserType := srcc.Type.(expr.UserType)
	switch {
	case expr.IsArray(srcc.Type):
		return transformArray(expr.AsArray(srcc.Type), expr.AsArray(tgtc.Type), srcVar, tgtVar, false, false, false, ta)
	case expr.IsMap(srcc.Type):
		return transformMap(expr.AsMap(srcc.Type), expr.AsMap(tgtc.Type), srcVar, tgtVar, false, false, ta)
	case isUserType:
		if !expr.IsPrimitive(srcc.Type) {
			return renderJenLine(exprCode(tgtVar).Op("=").Add(exprCode(renderTransformHelperCall(srcc, tgtc, srcVar, ta)))), nil
		}
		return "", nil
	case expr.IsObject(srcc.Type):
		return transformAttribute(srcc, tgtc, srcVar, tgtVar, false, ta)
	case expr.IsUnion(srcc.Type):
		if ta.proto {
			return transformUnionToProto(srcc, tgtc, srcVar, tgtVar, false, ta)
		}
		return transformUnionFromProto(srcc, tgtc, srcVar, tgtVar, ta)
	default:
		return "", nil
	}
}

func wrapObjectFieldNilCheck(code, srcVar string, srcMatt *expr.MappedAttributeExpr, srcc *expr.AttributeExpr, n string, ta *transformAttrs) string {
	if code == "" {
		return code
	}
	isRef := !expr.IsPrimitive(srcc.Type) && !srcMatt.IsRequired(n) || ta.SourceCtx.IsPrimitivePointer(n, srcMatt.AttributeExpr) && expr.IsPrimitive(srcc.Type)
	marshalNonPrimitive := !expr.IsPrimitive(srcc.Type)
	if !(isRef || marshalNonPrimitive) {
		return code
	}
	cond := "if " + srcVar + " != nil {\n"
	if expr.IsUnion(srcc.Type) && ta.proto {
		cond = "if " + srcVar + `.Kind() != "" {` + "\n"
	}
	return cond + "\t" + code + "}\n"
}

func applyObjectFieldDefaults(code, srcVar, tgtVar string, srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string, ta *transformAttrs) string {
	tdef := tgtMatt.GetDefault(n)
	if tdef == nil || !ta.TargetCtx.UseDefault || ta.TargetCtx.Pointer || srcMatt.IsRequired(n) {
		return code
	}
	switch {
	case ta.SourceCtx.IsPrimitivePointer(n, srcMatt.AttributeExpr) || !expr.IsPrimitive(srcc.Type):
		code += "if " + srcVar + " == nil {\n\t"
		if ta.TargetCtx.IsPrimitivePointer(n, tgtMatt.AttributeExpr) && expr.IsPrimitive(tgtc.Type) {
			nativeTypeName := codegen.GoNativeTypeName(tgtc.Type)
			if ta.proto {
				nativeTypeName = protoBufNativeGoTypeName(tgtc.Type)
			}
			code += "var tmp " + nativeTypeName + " = " + protobufDefaultLiteral(tgtc, tdef, ta) + "\n\t" + tgtVar + " = &tmp\n"
		} else {
			code += tgtVar + " = " + protobufDefaultLiteral(tgtc, tdef, ta) + "\n"
		}
		code += "}\n"
	case expr.IsPrimitive(srcc.Type) && srcMatt.HasDefaultValue(n) && ta.SourceCtx.UseDefault:
		code += "{\n\t"
		code += objectFieldZeroValueDecl(tgtc, ta)
		code += "if " + tgtVar + " == zero {\n\t" + tgtVar + " = " + protobufDefaultLiteral(tgtc, tdef, ta) + "\n}\n"
		code += "}\n"
	}
	return code
}

func objectFieldZeroValueDecl(tgtc *expr.AttributeExpr, ta *transformAttrs) string {
	if ta.proto {
		return "var zero " + protoBufNativeGoTypeName(tgtc.Type) + "\n\t"
	}
	if typeName, _ := codegen.GetMetaType(tgtc); typeName != "" {
		return "var zero " + typeName + "\n\t"
	}
	if _, ok := tgtc.Type.(expr.UserType); ok {
		return "var zero " + ta.TargetCtx.Scope.Ref(tgtc, ta.TargetCtx.Pkg(tgtc)) + "\n\t"
	}
	return "var zero " + codegen.GoNativeTypeName(tgtc.Type) + "\n\t"
}

func transformObjectPrimitivePointerCases(
	srcMatt *expr.MappedAttributeExpr,
	srcc, tgtc *expr.AttributeExpr,
	srcField, tgtField, srcFieldConv string,
	srcPtr, tgtPtr bool,
	targetVar, postInitCode string,
	elemName, attrName string,
	ta *transformAttrs,
) (string, string, bool) {
	_, isSrcUT := srcc.Type.(expr.UserType)
	_, isTgtUT := tgtc.Type.(expr.UserType)
	switch {
	case isSrcUT || isTgtUT || (srcField != srcFieldConv):
		exp := convertedPrimitiveObjectFieldExpr(srcc, tgtc, srcField, srcFieldConv, srcPtr, ta)
		initExp, postAssign, handled := transformassign.BuildPrimitiveObjectAssignment(transformassign.PrimitiveObjectPlan{
			SourceField:    srcField,
			TargetVar:      targetVar,
			TargetField:    tgtField,
			Expression:     exp,
			TempVar:        codegen.Goify(elemName, false),
			SourcePointer:  srcPtr,
			TargetPointer:  tgtPtr,
			SourceRequired: srcMatt.IsRequired(attrName),
		})
		if handled {
			return "", postInitCode + postAssign, true
		}
		return initExp, postInitCode, false
	case srcPtr && !tgtPtr:
		exp := "*" + srcField
		if !srcMatt.IsRequired(attrName) {
			_, postAssign, _ := transformassign.BuildPrimitiveObjectAssignment(transformassign.PrimitiveObjectPlan{
				SourceField:    srcField,
				TargetVar:      targetVar,
				TargetField:    tgtField,
				Expression:     exp,
				SourcePointer:  true,
				SourceRequired: false,
			})
			postInitCode += postAssign
			return "", postInitCode, true
		}
		return exp, postInitCode, false
	case !srcPtr && tgtPtr:
		return "&" + srcField, postInitCode, false
	default:
		return srcField, postInitCode, false
	}
}

func convertedPrimitiveObjectFieldExpr(srcc, tgtc *expr.AttributeExpr, srcField, srcFieldConv string, srcPtr bool, ta *transformAttrs) string {
	var deref string
	if srcPtr {
		deref = "*"
	}
	exp := srcFieldConv
	if _, isSrcUT := srcc.Type.(expr.UserType); isSrcUT && !ta.proto {
		exp = ta.TargetCtx.Scope.Ref(tgtc, ta.TargetCtx.Pkg(tgtc)) + "(" + deref + srcField + ")"
	}
	return exp
}

// transformArray returns the code to transform source attribute of array
// type to target attribute of array type. It returns an error if source
// and target are not compatible for transformation.
