package codegen

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/CaliLuke/loom/codegen"
	"github.com/CaliLuke/loom/dsl"
	"github.com/CaliLuke/loom/grpc/codegen/testdata"
)

func TestAnyProtoConstructorsPropagateConversionErrors(t *testing.T) {
	root := RunGRPCDSL(t, testdata.AnyErrorDSL)
	services := CreateGRPCServices(root)

	files := ClientTypeFiles("", services)
	require.Len(t, files, 1)
	var generated bytes.Buffer
	for _, section := range files[0].AllSections()[1:] {
		require.NoError(t, section.Write(&generated))
	}
	code := codegen.FormatTestCode(t, "package client\n"+generated.String())
	require.Contains(t, code, "transformErr := new(error)")
	require.Contains(t, code, "loomgrpc.NewProtoValue")
	require.Contains(t, code, "return zero, *transformErr")
	require.Contains(t, code, "return message, nil")
}

func TestAnyProtoEncodersReturnConstructorErrors(t *testing.T) {
	root := RunGRPCDSL(t, testdata.AnyErrorDSL)
	services := CreateGRPCServices(root)

	requestCode := codegen.SectionsCode(t, ClientFiles("", services)[1].Section("request-encoder"))
	require.Contains(t, requestCode, "return NewProtoConvertRequest(payload)")
	require.NotContains(t, requestCode, "return NewProtoConvertRequest(payload), nil")

	responseCode := codegen.SectionsCode(t, ServerFiles("", services)[1].Section("response-encoder"))
	require.Contains(t, responseCode, "resp, err :=")
	require.Contains(t, responseCode, "if err != nil")
	require.Contains(t, responseCode, "return nil, err")
}

// TestAnyProtoMessagesImportStructProto checks that the proto file imports
// google/protobuf/struct.proto whenever a message uses google.protobuf.Value,
// including when the Any value is wrapped in a user type such as a OneOf
// branch or a type alias.
func TestAnyProtoMessagesImportStructProto(t *testing.T) {
	cases := []struct {
		Name    string
		Payload func() any
	}{
		{"any-field", func() any {
			return dsl.Type("Message", func() {
				dsl.Field(1, "value", dsl.Any)
			})
		}},
		{"any-oneof-branch", func() any {
			return dsl.Type("Message", func() {
				dsl.OneOf("pick", func() {
					dsl.Field(1, "text", dsl.String)
					dsl.Field(2, "value", dsl.Any)
				})
			})
		}},
		{"any-alias-field", func() any {
			blob := dsl.Type("Blob", dsl.Any)
			return dsl.Type("Message", func() {
				dsl.Field(1, "value", blob)
			})
		}},
		{"top-level-union-with-any-alias", func() any {
			label := dsl.Type("Label", dsl.String)
			blob := dsl.Type("Blob", dsl.Any)
			return dsl.OneOf(label, blob)
		}},
	}
	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			root := RunGRPCDSL(t, func() {
				payload := c.Payload()
				dsl.Service("converter", func() {
					dsl.Method("convert", func() {
						dsl.Payload(payload)
						dsl.Result(dsl.String)
						dsl.GRPC(func() {})
					})
				})
			})
			sd := CreateGRPCServices(root).Get("converter")
			require.Contains(t, sd.ProtoImports, "google/protobuf/struct.proto")
		})
	}
}

// TestAnyOneOfBranchConvertsFromProtobufValue checks that the server and
// client CLI payload constructors convert a google.protobuf.Value OneOf
// branch to the loom.JSONValue alias of the service union branch instead of
// casting the protobuf message to it.
func TestAnyOneOfBranchConvertsFromProtobufValue(t *testing.T) {
	design := func() {
		payload := dsl.Type("Message", func() {
			dsl.OneOf("pick", func() {
				dsl.Field(1, "text", dsl.String)
				dsl.Field(2, "value", dsl.Any)
			})
		})
		dsl.Service("converter", func() {
			dsl.Method("convert", func() {
				dsl.Payload(payload)
				dsl.Result(dsl.String)
				dsl.GRPC(func() {})
			})
		})
	}
	cases := []struct {
		Name  string
		Files func(*ServicesData) []*codegen.File
	}{
		{"server-types", func(services *ServicesData) []*codegen.File {
			return ServerTypeFiles("", services)
		}},
		{"client-cli", func(services *ServicesData) []*codegen.File {
			return ClientCLIFiles("", services)[1:]
		}},
	}
	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			services := CreateGRPCServices(RunGRPCDSL(t, design))
			files := c.Files(services)
			require.Len(t, files, 1)
			var generated bytes.Buffer
			for _, section := range files[0].AllSections() {
				require.NoError(t, section.Write(&generated))
			}
			code := codegen.FormatTestCode(t, generated.String())
			require.Contains(t, code, "u.SetValue(func() loom.JSONValue {")
			require.Contains(t, code, "loomgrpc.NewJSONValue(val.Value)")
			require.NotContains(t, code, "converter.PickValue(val.Value)")
		})
	}
}
