package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/CaliLuke/loom/codegen"
	"github.com/CaliLuke/loom/expr"
	"github.com/CaliLuke/loom/internal/transformassign"
)

type transformAttrs struct {
	*codegen.TransformAttrs
	// proto if true indicates that the transformation code is used to initialize
	// a protocol buffer type from a service type. If false, the transformation
	// code is used to initialize a service type from a protocol buffer type.
	proto bool
	// targetInit is the initialization code for the target type for nested
	// map and array types.
	targetInit string
	// wrapped indicates whether the source or target is in a wrapped state.
	// See grpc/docs/FAQ.md. `wrapped` is true and `proto` is true indicates
	// the target attribute is in wrapped state. `wrapped` is true and `proto`
	// is false indicates the source attribute is in wrapped state.
	wrapped bool
	// message is the reference to the Go type generated by protoc for the
	// source message when proto is false.  (protoc builds union struct type
	// names from the parent message name).
	message string
}

// unionData is used by both transformUnion methods.
type unionData struct {
	Source              *expr.Union
	Target              *expr.Union
	SourceValues        []*expr.NamedAttributeExpr
	TargetValues        []*expr.NamedAttributeExpr
	SourceValueTypeRefs []string
	// TargetWrapperRefs holds wrapper type refs used when assigning from
	// protobuf to Go union (proto -> Go). Empty string means no wrapper.
	TargetWrapperRefs []string
}

// protoBufTransform produces Go code to initialize a data structure defined
// by target from an instance of data structure defined by source. The source
// or target is a protocol buffer type.
//
// source, target are the source and target attributes used in transformation
//
// sourceVar, targetVar are the source and target variables
//
// sourceCtx, targetCtx are the source and target attribute contexts
//
// `proto` param if true indicates that the target is a protocol buffer type
//
// newVar if true initializes a target variable with the generated Go code
// using `:=` operator. If false, it assigns Go code to the target variable
// using `=`.
func protoBufTransform(source, target *expr.AttributeExpr, sourceVar, targetVar string, sourceCtx, targetCtx *codegen.AttributeContext, proto, newVar bool) (string, []*codegen.TransformFunctionData, error) {
	ta := &transformAttrs{TransformAttrs: &codegen.TransformAttrs{
		SourceCtx: sourceCtx,
		TargetCtx: targetCtx,
	}}
	if proto {
		target = expr.DupAtt(target)
		removeMeta(target)
		ta.Prefix = "svc"
		ta.proto = true
	} else {
		source = expr.DupAtt(source)
		removeMeta(source)
		ta.Prefix = "protobuf"
		ta.proto = false
	}

	code, err := transformAttribute(source, target, sourceVar, targetVar, newVar, ta)
	if err != nil {
		return "", nil, err
	}

	funcs, err := transformAttributeHelpers(source, target, ta, make(map[string]*codegen.TransformFunctionData))
	if err != nil {
		return "", nil, err
	}

	return strings.TrimRight(code, "\n"), funcs, nil
}

// removeMeta removes meta attributes from the given attribute that cannot be
// honored. This is needed to make sure that any field name overridding is
// removed when generating protobuf types (as protogen itself won't honor these
// overrides).
func removeMeta(att *expr.AttributeExpr) {
	_ = codegen.Walk(att, func(a *expr.AttributeExpr) error {
		delete(a.Meta, "struct:field:name")
		delete(a.Meta, "struct:field:external")
		delete(a.Meta, "struct.field.external") // Deprecated syntax. Only present for backward compatibility.
		return nil
	})
}

// transformAttribute returns the code to initialize a target data structure
// from an instance of source data structure. It returns an error if source and
// target are not compatible for transformation (different types, fields of
// different type).
func transformAttribute(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, error) {
	var (
		initCode string
		err      error
	)

	if err := codegen.IsCompatible(source.Type, target.Type, sourceVar, targetVar); err != nil {
		if ta.proto {
			name := ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
			initCode += fmt.Sprintf("%s := &%s{}\n", targetVar, name)
			targetVar += ".Field"
			newVar = false
			target = unwrapAttr(expr.DupAtt(target))
		} else {
			source = unwrapAttr(expr.DupAtt(source))
			sourceVar += ".Field"
		}
		if err = codegen.IsCompatible(source.Type, target.Type, sourceVar, targetVar); err != nil {
			return "", err
		}
	}

	if ta.proto {
		if isUnionMessage(target) {
			ta = dupTransformAttrs(ta)
			ta.message = ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), false, false)
		}
	} else {
		if isUnionMessage(source) {
			ta = dupTransformAttrs(ta)
			ta.message = ta.SourceCtx.Scope.Ref(source, ta.SourceCtx.Pkg(source))
		}
	}

	code, err := transformAttributeByKind(source, target, sourceVar, targetVar, newVar, ta)
	if err != nil {
		return "", err
	}
	// Ensure code ends with newline for proper formatting when used in templates
	if code != "" && !strings.HasSuffix(code, "\n") {
		code += "\n"
	}
	return initCode + code, nil
}

func transformAttributeByKind(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, error) {
	switch {
	case expr.IsArray(source.Type):
		// Top-level array transforms never assign into a pointer field.
		return transformArray(expr.AsArray(source.Type), expr.AsArray(target.Type), sourceVar, targetVar, newVar, false, false, ta)
	case expr.IsMap(source.Type):
		return transformMap(expr.AsMap(source.Type), expr.AsMap(target.Type), sourceVar, targetVar, newVar, false, ta)
	case expr.IsObject(source.Type):
		return transformObject(source, target, sourceVar, targetVar, newVar, ta)
	case expr.IsUnion(source.Type):
		if ta.proto {
			// At top-level we do not expect pointer-to-interface unions.
			return transformUnionToProto(source, target, sourceVar, targetVar, false, ta)
		}
		return transformUnionFromProto(source, target, sourceVar, targetVar, ta)
	case source.Type.Kind() == expr.AnyKind || target.Type.Kind() == expr.AnyKind:
		return transformScalarAssignment(source, target, sourceVar, targetVar, newVar, ta), nil
	default:
		return transformScalarAssignment(source, target, sourceVar, targetVar, newVar, ta), nil
	}
}

func transformScalarAssignment(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) string {
	assign := "="
	if newVar {
		assign = ":="
	}
	srcField := convertType(source, target, false, false, sourceVar, ta)
	return fmt.Sprintf("%s %s %s\n", targetVar, assign, srcField)
}

// transformObject returns the code to transform source attribute of object
// type to target attribute of object type. It returns an error if source
// and target are not compatible for transformation.
func transformObject(source, target *expr.AttributeExpr, sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, error) {
	initCode, postInitCode := buildPrimitiveObjectInit(source, target, sourceVar, targetVar, ta)

	buffer := &bytes.Buffer{}
	deref := "&"
	// if the target is a raw struct no need to return a pointer
	if _, ok := target.Type.(*expr.Object); ok {
		deref = ""
	}
	assign := "="
	if newVar {
		assign = ":="
	}
	tname := ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
	fmt.Fprintf(buffer, "%s %s %s%s{%s}\n", targetVar, assign, deref, tname, initCode)
	buffer.WriteString(postInitCode)

	var err error
	walkMatches(source, target, func(srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string) {
		code, fieldErr := buildObjectFieldTransform(target, sourceVar, targetVar, srcMatt, tgtMatt, srcc, tgtc, n, ta)
		if fieldErr != nil {
			err = fieldErr
			return
		}
		buffer.WriteString(code)
	})
	if err != nil {
		return "", err
	}

	return buffer.String(), nil
}

func buildPrimitiveObjectInit(source, target *expr.AttributeExpr, sourceVar, targetVar string, ta *transformAttrs) (string, string) {
	var (
		initCode     string
		postInitCode string
	)
	walkMatches(source, target, func(srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string) {
		if !expr.IsPrimitive(srcc.Type) {
			return
		}
		srcField := sourceVar + "." + ta.SourceCtx.Scope.Field(srcc, srcMatt.ElemName(n), true)
		tgtField := ta.TargetCtx.Scope.Field(tgtc, tgtMatt.ElemName(n), true)
		srcPtr := ta.SourceCtx.IsPrimitivePointer(n, srcMatt.AttributeExpr)
		tgtPtr := ta.TargetCtx.IsPrimitivePointer(n, tgtMatt.AttributeExpr)
		srcFieldConv := convertType(srcc, tgtc, srcPtr, tgtPtr, srcField, ta)
		exp, updatedPostInit, handled := transformObjectPrimitivePointerCases(
			srcMatt, srcc, tgtc, srcField, tgtField, srcFieldConv, srcPtr, tgtPtr, targetVar, postInitCode, tgtMatt.ElemName(n), n, ta,
		)
		postInitCode = updatedPostInit
		if handled {
			return
		}
		initCode += fmt.Sprintf("\n%s: %s,", tgtField, exp)
	})
	if initCode != "" {
		initCode += "\n"
	}
	return initCode, postInitCode
}

func buildObjectFieldTransform(target *expr.AttributeExpr, sourceVar, targetVar string, srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string, ta *transformAttrs) (string, error) {
	srcc = unAlias(srcc)
	tgtc = unAlias(tgtc)
	srcValue := sourceVar + "." + ta.SourceCtx.Scope.Field(srcc, srcMatt.ElemName(n), true)
	tgtValue := targetVar + "." + ta.TargetCtx.Scope.Field(tgtc, tgtMatt.ElemName(n), true)
	compatibleSource, compatibleTarget, err := compatibleTransformAttrs(srcc, tgtc, ta)
	if err != nil {
		return "", err
	}
	code, err := objectFieldAssignment(target, targetVar, srcValue, tgtValue, tgtMatt, compatibleSource, compatibleTarget, n, ta)
	if err != nil {
		return "", err
	}
	code = wrapObjectFieldNilCheck(code, srcValue, srcMatt, compatibleSource, n, ta)
	return applyObjectFieldDefaults(code, srcValue, tgtValue, srcMatt, tgtMatt, compatibleSource, compatibleTarget, n, ta), nil
}

func compatibleTransformAttrs(srcc, tgtc *expr.AttributeExpr, ta *transformAttrs) (*expr.AttributeExpr, *expr.AttributeExpr, error) {
	if err := codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err == nil {
		return srcc, tgtc, nil
	}
	if ta.proto {
		ta.targetInit = ta.TargetCtx.Scope.Name(tgtc, ta.TargetCtx.Pkg(tgtc), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
		tgtc = unwrapAttr(tgtc)
	} else {
		srcc = unwrapAttr(srcc)
	}
	ta.wrapped = true
	if err := codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err != nil {
		return nil, nil, err
	}
	return srcc, tgtc, nil
}

func objectFieldAssignment(target *expr.AttributeExpr, targetVar, srcVar, tgtVar string, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string, ta *transformAttrs) (string, error) {
	_, isUserType := srcc.Type.(expr.UserType)
	switch {
	case expr.IsArray(srcc.Type):
		return transformArray(expr.AsArray(srcc.Type), expr.AsArray(tgtc.Type), srcVar, tgtVar, false, false, false, ta)
	case expr.IsMap(srcc.Type):
		return transformMap(expr.AsMap(srcc.Type), expr.AsMap(tgtc.Type), srcVar, tgtVar, false, false, ta)
	case isUserType:
		if ta.TargetCtx.IsInterface {
			ref := ta.TargetCtx.Scope.Ref(target, ta.TargetCtx.Pkg(target))
			tgtVar = targetVar + ".(" + ref + ")." + codegen.GoifyAtt(tgtc, tgtMatt.ElemName(n), true)
		}
		if !expr.IsPrimitive(srcc.Type) {
			return fmt.Sprintf("%s = %s(%s)\n", tgtVar, transformHelperName(srcc, tgtc, ta), srcVar), nil
		}
		return "", nil
	case expr.IsObject(srcc.Type):
		return transformAttribute(srcc, tgtc, srcVar, tgtVar, false, ta)
	case expr.IsUnion(srcc.Type):
		if ta.proto {
			return transformUnionToProto(srcc, tgtc, srcVar, tgtVar, false, ta)
		}
		return transformUnionFromProto(srcc, tgtc, srcVar, tgtVar, ta)
	default:
		return "", nil
	}
}

func wrapObjectFieldNilCheck(code, srcVar string, srcMatt *expr.MappedAttributeExpr, srcc *expr.AttributeExpr, n string, ta *transformAttrs) string {
	if code == "" {
		return code
	}
	isRef := !expr.IsPrimitive(srcc.Type) && !srcMatt.IsRequired(n) || ta.SourceCtx.IsPrimitivePointer(n, srcMatt.AttributeExpr) && expr.IsPrimitive(srcc.Type)
	marshalNonPrimitive := !expr.IsPrimitive(srcc.Type)
	if !(isRef || marshalNonPrimitive) {
		return code
	}
	cond := fmt.Sprintf("if %s != nil {\n", srcVar)
	if expr.IsUnion(srcc.Type) && ta.proto {
		cond = fmt.Sprintf("if %s.Kind() != \"\" {\n", srcVar)
	}
	return fmt.Sprintf("%s\t%s}\n", cond, code)
}

func applyObjectFieldDefaults(code, srcVar, tgtVar string, srcMatt, tgtMatt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string, ta *transformAttrs) string {
	tdef := tgtMatt.GetDefault(n)
	if tdef == nil || !ta.TargetCtx.UseDefault || ta.TargetCtx.Pointer || srcMatt.IsRequired(n) {
		return code
	}
	switch {
	case ta.SourceCtx.IsPrimitivePointer(n, srcMatt.AttributeExpr) || !expr.IsPrimitive(srcc.Type):
		code += fmt.Sprintf("if %s == nil {\n\t", srcVar)
		if ta.TargetCtx.IsPrimitivePointer(n, tgtMatt.AttributeExpr) && expr.IsPrimitive(tgtc.Type) {
			nativeTypeName := codegen.GoNativeTypeName(tgtc.Type)
			if ta.proto {
				nativeTypeName = protoBufNativeGoTypeName(tgtc.Type)
			}
			code += fmt.Sprintf("var tmp %s = %#v\n\t%s = &tmp\n", nativeTypeName, tdef, tgtVar)
		} else {
			code += fmt.Sprintf("%s = %#v\n", tgtVar, tdef)
		}
		code += "}\n"
	case expr.IsPrimitive(srcc.Type) && srcMatt.HasDefaultValue(n) && ta.SourceCtx.UseDefault:
		code += "{\n\t"
		code += objectFieldZeroValueDecl(tgtc, ta)
		code += fmt.Sprintf("if %s == zero {\n\t%s = %#v\n}\n", tgtVar, tgtVar, tdef)
		code += "}\n"
	}
	return code
}

func objectFieldZeroValueDecl(tgtc *expr.AttributeExpr, ta *transformAttrs) string {
	if ta.proto {
		return fmt.Sprintf("var zero %s\n\t", protoBufNativeGoTypeName(tgtc.Type))
	}
	if typeName, _ := codegen.GetMetaType(tgtc); typeName != "" {
		return fmt.Sprintf("var zero %s\n\t", typeName)
	}
	if _, ok := tgtc.Type.(expr.UserType); ok {
		return fmt.Sprintf("var zero %s\n\t", ta.TargetCtx.Scope.Ref(tgtc, ta.TargetCtx.Pkg(tgtc)))
	}
	return fmt.Sprintf("var zero %s\n\t", codegen.GoNativeTypeName(tgtc.Type))
}

func transformObjectPrimitivePointerCases(
	srcMatt *expr.MappedAttributeExpr,
	srcc, tgtc *expr.AttributeExpr,
	srcField, tgtField, srcFieldConv string,
	srcPtr, tgtPtr bool,
	targetVar, postInitCode string,
	elemName, attrName string,
	ta *transformAttrs,
) (string, string, bool) {
	_, isSrcUT := srcc.Type.(expr.UserType)
	_, isTgtUT := tgtc.Type.(expr.UserType)
	switch {
	case isSrcUT || isTgtUT || (srcField != srcFieldConv):
		exp := convertedPrimitiveObjectFieldExpr(srcc, tgtc, srcField, srcFieldConv, srcPtr, ta)
		initExp, postAssign, handled := transformassign.BuildPrimitiveObjectAssignment(transformassign.PrimitiveObjectPlan{
			SourceField:    srcField,
			TargetVar:      targetVar,
			TargetField:    tgtField,
			Expression:     exp,
			TempVar:        codegen.Goify(elemName, false),
			SourcePointer:  srcPtr,
			TargetPointer:  tgtPtr,
			SourceRequired: srcMatt.IsRequired(attrName),
		})
		if handled {
			return "", postInitCode + postAssign, true
		}
		return initExp, postInitCode, false
	case srcPtr && !tgtPtr:
		exp := "*" + srcField
		if !srcMatt.IsRequired(attrName) {
			_, postAssign, _ := transformassign.BuildPrimitiveObjectAssignment(transformassign.PrimitiveObjectPlan{
				SourceField:    srcField,
				TargetVar:      targetVar,
				TargetField:    tgtField,
				Expression:     exp,
				SourcePointer:  true,
				SourceRequired: false,
			})
			postInitCode += postAssign
			return "", postInitCode, true
		}
		return exp, postInitCode, false
	case !srcPtr && tgtPtr:
		return "&" + srcField, postInitCode, false
	default:
		return srcField, postInitCode, false
	}
}

func convertedPrimitiveObjectFieldExpr(srcc, tgtc *expr.AttributeExpr, srcField, srcFieldConv string, srcPtr bool, ta *transformAttrs) string {
	var deref string
	if srcPtr {
		deref = "*"
	}
	exp := srcFieldConv
	if _, isSrcUT := srcc.Type.(expr.UserType); isSrcUT && !ta.proto {
		exp = fmt.Sprintf("%s(%s%s)", ta.TargetCtx.Scope.Ref(tgtc, ta.TargetCtx.Pkg(tgtc)), deref, srcField)
	}
	return exp
}

// transformArray returns the code to transform source attribute of array
// type to target attribute of array type. It returns an error if source
// and target are not compatible for transformation.
func transformArray(source, target *expr.Array, sourceVar, targetVar string, newVar bool, targetPtr bool, sourcePtr bool, ta *transformAttrs) (string, error) {
	elem := target.ElemType
	if ta.proto {
		elem = unAlias(elem)
	}
	targetRef := ta.TargetCtx.Scope.Ref(elem, ta.TargetCtx.Pkg(elem))

	var (
		code string
		err  error
	)

	// If targetInit is set, the target array element is in a nested state.
	// See grpc/docs/FAQ.md.
	if ta.targetInit != "" {
		assign := "="
		if newVar {
			assign = ":="
		}
		code = fmt.Sprintf("%s %s &%s{}\n", targetVar, assign, ta.targetInit)
		ta.targetInit = ""
	}
	if ta.wrapped {
		if ta.proto {
			targetVar += ".Field"
			newVar = false
		} else {
			sourceVar += ".Field"
		}
		ta.wrapped = false
	}

	src := source.ElemType
	tgt := elem
	if err = codegen.IsCompatible(src.Type, tgt.Type, "[0]", "[0]"); err != nil {
		if ta.proto {
			ta.targetInit = ta.TargetCtx.Scope.Name(tgt, ta.TargetCtx.Pkg(tgt), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
			tgt = unwrapAttr(expr.DupAtt(tgt))
		} else {
			src = unwrapAttr(expr.DupAtt(src))
		}
		ta.wrapped = true
		if err = codegen.IsCompatible(src.Type, tgt.Type, "[0]", "[0]"); err != nil {
			return "", err
		}
	}
	valVar := "val"
	if obj := expr.AsObject(src.Type); obj != nil {
		if len(*obj) == 0 {
			valVar = ""
		}
	}

	var (
		buf     bytes.Buffer
		loopVar = string(rune(105 + strings.Count(targetVar, "[")))
		rangeOn = sourceVar
		assign  = "="
	)
	if sourcePtr {
		rangeOn = "*" + rangeOn
	}
	if newVar {
		assign = ":="
	}
	sourceValue := "val"
	targetElemVar := fmt.Sprintf("%s[%s]", targetVar, loopVar)
	if targetPtr {
		arrayVar := fmt.Sprintf("arr%s", loopVar)
		targetElemVar = fmt.Sprintf("%s[%s]", arrayVar, loopVar)
		fmt.Fprintf(&buf, "%s := make([]%s, len(%s))\n", arrayVar, targetRef, rangeOn)
	} else {
		fmt.Fprintf(&buf, "%s %s make([]%s, len(%s))\n", targetVar, assign, targetRef, rangeOn)
	}
	if valVar != "" {
		fmt.Fprintf(&buf, "for %s, %s := range %s {\n", loopVar, valVar, rangeOn)
	} else {
		fmt.Fprintf(&buf, "for %s := range %s {\n", loopVar, rangeOn)
	}
	elemCode, err := transformAttribute(src, tgt, sourceValue, targetElemVar, false, ta)
	if err != nil {
		return "", err
	}
	buf.WriteString(codegen.Indent(elemCode, "\t"))
	buf.WriteString("}\n")
	if targetPtr {
		fmt.Fprintf(&buf, "%s = &arr%s\n", targetVar, loopVar)
	}
	return code + buf.String(), nil
}

// transformMap returns the code to transform source attribute of map
// type to target attribute of map type. It returns an error if source
// and target are not compatible for transformation.
func transformMap(source, target *expr.Map, sourceVar, targetVar string, newVar bool, targetPtr bool, ta *transformAttrs) (string, error) {
	// Target map key cannot be nested in protocol buffers. So no need to worry
	// about unwrapping.
	if err := codegen.IsCompatible(source.KeyType.Type, target.KeyType.Type, sourceVar+"[key]", targetVar+"[key]"); err != nil {
		return "", err
	}
	targetKeyRef, targetElemRef := transformMapTypeRefs(target, ta)
	code, sourceVar, targetVar, newVar := transformMapTargetSetup(sourceVar, targetVar, newVar, ta)
	src, tgt, err := transformMapElementAttrs(source, target, ta)
	if err != nil {
		return "", err
	}
	loopVar, suffix := transformMapLoopNames(target)
	mapVar, initCode := transformMapInit(targetVar, sourceVar, targetPtr, targetKeyRef, targetElemRef, newVar, loopVar)
	var buf bytes.Buffer
	buf.WriteString(initCode)
	fmt.Fprintf(&buf, "for key, val := range %s {\n", sourceVar)
	keyCode, err := transformAttribute(source.KeyType, target.KeyType, "key", "tk", true, ta)
	if err != nil {
		return "", err
	}
	buf.WriteString(codegen.Indent(keyCode, "\t"))
	elemTmp := fmt.Sprintf("tv%s", suffix)
	elemCode, err := transformAttribute(src, tgt, "val", elemTmp, true, ta)
	if err != nil {
		return "", err
	}
	buf.WriteString(codegen.Indent(elemCode, "\t"))
	fmt.Fprintf(&buf, "\t%s[tk] = %s\n", mapVar, elemTmp)
	buf.WriteString("}\n")
	if targetPtr {
		fmt.Fprintf(&buf, "%s = &%s\n", targetVar, mapVar)
	}
	return code + buf.String(), nil
}

func transformMapTypeRefs(target *expr.Map, ta *transformAttrs) (string, string) {
	kt := target.KeyType
	et := target.ElemType
	if ta.proto {
		kt = unAlias(kt)
		et = unAlias(et)
	}
	return ta.TargetCtx.Scope.Ref(kt, ta.TargetCtx.Pkg(kt)), ta.TargetCtx.Scope.Ref(et, ta.TargetCtx.Pkg(et))
}

func transformMapTargetSetup(sourceVar, targetVar string, newVar bool, ta *transformAttrs) (string, string, string, bool) {
	code := ""
	if ta.targetInit != "" {
		assign := "="
		if newVar {
			assign = ":="
		}
		code = fmt.Sprintf("%s %s &%s{}\n", targetVar, assign, ta.targetInit)
		ta.targetInit = ""
	}
	if !ta.wrapped {
		return code, sourceVar, targetVar, newVar
	}
	if ta.proto {
		targetVar += ".Field"
		newVar = false
	} else {
		sourceVar += ".Field"
	}
	ta.wrapped = false
	return code, sourceVar, targetVar, newVar
}

func transformMapElementAttrs(source, target *expr.Map, ta *transformAttrs) (*expr.AttributeExpr, *expr.AttributeExpr, error) {
	src := source.ElemType
	tgt := target.ElemType
	if err := codegen.IsCompatible(src.Type, tgt.Type, "[*]", "[*]"); err == nil {
		return src, tgt, nil
	}
	if ta.proto {
		ta.targetInit = ta.TargetCtx.Scope.Name(tgt, ta.TargetCtx.Pkg(tgt), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault)
		tgt = unwrapAttr(expr.DupAtt(tgt))
	} else {
		src = unwrapAttr(expr.DupAtt(src))
	}
	ta.wrapped = true
	if err := codegen.IsCompatible(src.Type, tgt.Type, "[*]", "[*]"); err != nil {
		return nil, nil, err
	}
	return src, tgt, nil
}

func transformMapLoopNames(target *expr.Map) (string, string) {
	if depth := codegen.MapDepth(target); depth > 0 {
		loopVar := string(rune(97 + depth))
		return loopVar, loopVar
	}
	return "a", ""
}

func transformMapInit(targetVar, sourceVar string, targetPtr bool, targetKeyRef, targetElemRef string, newVar bool, loopVar string) (string, string) {
	assign := "="
	if newVar {
		assign = ":="
	}
	if targetPtr {
		mapVar := fmt.Sprintf("m%s", loopVar)
		return mapVar, fmt.Sprintf("%s := make(map[%s]%s, len(%s))\n", mapVar, targetKeyRef, targetElemRef, sourceVar)
	}
	return targetVar, fmt.Sprintf("%s %s make(map[%s]%s, len(%s))\n", targetVar, assign, targetKeyRef, targetElemRef, sourceVar)
}

// transformUnionToProto returns the code to transform an attribute of type
// union from protobuf to Loom. It returns an error if source and target are not
// compatible for transformation.
func transformUnionToProto(source, target *expr.AttributeExpr, sourceVar, targetVar string, sourcePtr bool, ta *transformAttrs) (string, error) {
	if err := codegen.IsCompatible(source.Type, target.Type, sourceVar, targetVar); err != nil {
		return "", err
	}
	tdata := transformUnionData(source, target, ta)
	cases := make([]map[string]any, 0, len(tdata.SourceValues))
	for i, sv := range tdata.SourceValues {
		tv := tdata.TargetValues[i]
		fieldName := ta.TargetCtx.Scope.Field(tv.Attribute, tv.Name, true)
		cases = append(cases, map[string]any{
			"typeTag":           sv.Name,
			"sourceFieldName":   codegen.Goify(sv.Name, true),
			"sourceAttr":        sv.Attribute,
			"targetAttr":        tv.Attribute,
			"targetWrapperType": ta.message + "_" + fieldName,
			"targetFieldName":   fieldName,
		})
	}

	var buf bytes.Buffer
	switchTarget := sourceVar
	if sourcePtr {
		switchTarget = "(*" + sourceVar + ")"
	}
	fmt.Fprintf(&buf, "switch string(%s.Kind()) {\n", switchTarget)
	for _, c := range cases {
		fmt.Fprintf(&buf, "case %q:\n", c["typeTag"])
		fmt.Fprintf(&buf, "\tactual, _ := %s.As%s()\n", switchTarget, c["sourceFieldName"])
		val := convertType(c["sourceAttr"].(*expr.AttributeExpr), c["targetAttr"].(*expr.AttributeExpr), false, false, "actual", ta)
		fmt.Fprintf(&buf, "\t%s = &%s{%s: %s}\n", targetVar, c["targetWrapperType"], c["targetFieldName"], val)
	}
	buf.WriteString("}\n")
	return buf.String(), nil
}

// transformUnionFromProto returns the code to transform an attribute of type
// union from protobuf to Loom. It returns an error if source and target are not
// compatible for transformation.
func transformUnionFromProto(source, target *expr.AttributeExpr, sourceVar, targetVar string, ta *transformAttrs) (string, error) {
	if err := codegen.IsCompatible(source.Type, target.Type, sourceVar, targetVar); err != nil {
		return "", err
	}
	tdata := transformUnionData(source, target, ta)
	cases := make([]map[string]any, 0, len(tdata.SourceValues))
	for i, sv := range tdata.SourceValues {
		tv := tdata.TargetValues[i]
		sourceFieldName := ta.SourceCtx.Scope.Field(sv.Attribute, sv.Name, true)
		targetFieldName := codegen.Goify(tv.Name, true)
		cases = append(cases, map[string]any{
			"sourceValueTypeRef": tdata.SourceValueTypeRefs[i],
			"sourceFieldName":    sourceFieldName,
			"sourceAttr":         sv.Attribute,
			"targetAttr":         tv.Attribute,
			"targetFieldName":    targetFieldName,
		})
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "switch val := %s.(type) {\n", sourceVar)
	for _, c := range cases {
		fmt.Fprintf(&buf, "case %s:\n", c["sourceValueTypeRef"])
		field := "val." + c["sourceFieldName"].(string)
		tmp := convertType(c["sourceAttr"].(*expr.AttributeExpr), c["targetAttr"].(*expr.AttributeExpr), false, false, field, ta)
		buf.WriteString("\t{\n")
		fmt.Fprintf(&buf, "\t\tu := %s\n", targetVar)
		fmt.Fprintf(&buf, "\t\tu.Set%s(%s)\n", c["targetFieldName"], tmp)
		fmt.Fprintf(&buf, "\t\t%s = u\n", targetVar)
		buf.WriteString("\t}\n")
	}
	buf.WriteString("}\n")
	return buf.String(), nil
}

// convertType produces code to initialize a target type from a source type
// held by sourceVar.
func convertType(src, tgt *expr.AttributeExpr, srcPtr bool, tgtPtr bool, srcVar string, ta *transformAttrs) string {
	if expr.IsAlias(src.Type) || expr.IsAlias(tgt.Type) {
		srcp, tgtp := unAlias(src), unAlias(tgt)
		if srcp.Type == tgtp.Type {
			if ta.proto {
				return convertPrimitiveToProto(src, tgtp, srcPtr, tgtPtr, srcVar, ta)
			}
			return convertPrimitiveFromProto(srcp, tgt, srcPtr, tgtPtr, srcVar, ta)
		}
		return fmt.Sprintf("%s(%s)", transformHelperName(src, tgt, ta), srcVar)
	}

	if _, ok := src.Type.(expr.UserType); ok {
		return fmt.Sprintf("%s(%s)", transformHelperName(src, tgt, ta), srcVar)
	}

	srcType, _ := codegen.GetMetaType(src)
	tgtType, _ := codegen.GetMetaType(tgt)
	if srcType == "" && tgtType == "" && (src.Type != expr.Int) && (src.Type != expr.UInt) && (src.Type != expr.Any) {
		// Nothing to do, except for Any type which needs special conversion
		return srcVar
	}

	if ta.proto {
		return convertPrimitiveToProto(src, tgt, srcPtr, tgtPtr, srcVar, ta)
	}
	return convertPrimitiveFromProto(src, tgt, srcPtr, tgtPtr, srcVar, ta)
}

const convertGoAnyToProtobufValueFunc = `func() *structpb.Value {
	// Convert Go any to protobuf Value directly
	if %s == nil {
		return structpb.NewNullValue()
	}
	value, err := structpb.NewValue(%s)
	if err != nil {
		panic(fmt.Sprintf("failed to convert value to structpb.Value: %%v", err))
	}
	return value
}()`

const convertProtobufValueToGoAnyFunc = `func() any {
	// Convert protobuf Value to Go any directly
	if %s != nil {
		return %s.AsInterface()
	}
	return nil
}()`

// convertPrimitive returns the code to convert a primitive type from one
// representation to another.
// NOTE: For Int and UInt kinds, protocol buffer Go compiler generates
// int32 and uint32 respectively whereas Loom generates int and uint.
func convertPrimitiveToProto(_, tgt *expr.AttributeExpr, srcPtr, _ bool, srcVar string, _ *transformAttrs) string {
	// Special handling for Any type conversion to google.protobuf.Value
	if tgt.Type.Kind() == expr.AnyKind {
		if srcPtr {
			srcVar = "*" + srcVar
		}

		return fmt.Sprintf(convertGoAnyToProtobufValueFunc, srcVar, srcVar)
	}

	tgtType := protoBufNativeGoTypeName(tgt.Type)
	if srcPtr {
		srcVar = "*" + srcVar
	}
	return fmt.Sprintf("%s(%s)", tgtType, srcVar)
}

func convertPrimitiveFromProto(_, tgt *expr.AttributeExpr, srcPtr, _ bool, srcVar string, ta *transformAttrs) string {
	// Special handling for Any type conversion from google.protobuf.Value
	if tgt.Type.Kind() == expr.AnyKind {
		if srcPtr {
			srcVar = "*" + srcVar
		}

		return fmt.Sprintf(convertProtobufValueToGoAnyFunc, srcVar, srcVar)
	}

	tgtType, _ := codegen.GetMetaType(tgt)
	if tgtType == "" {
		tgtType = ta.TargetCtx.Scope.Ref(tgt, ta.TargetCtx.Pkg(tgt))
	}
	if srcPtr {
		srcVar = "*" + srcVar
	}
	return fmt.Sprintf("%s(%s)", tgtType, srcVar)
}

// transformUnionData returns data needed by both transformUnion functions.
func transformUnionData(source, target *expr.AttributeExpr, ta *transformAttrs) *unionData {
	src := expr.AsUnion(source.Type)
	tgt := expr.AsUnion(target.Type)
	srcValues := make([]*expr.NamedAttributeExpr, len(src.Values))
	copy(srcValues, src.Values)
	tgtValues := make([]*expr.NamedAttributeExpr, len(tgt.Values))
	copy(tgtValues, tgt.Values)
	sourceValueTypeRefs, targetWrapperRefs := transformUnionTypeRefs(source, target, ta, src, tgt)
	return &unionData{
		Source:              src,
		Target:              tgt,
		SourceValues:        srcValues,
		TargetValues:        tgtValues,
		SourceValueTypeRefs: sourceValueTypeRefs,
		TargetWrapperRefs:   targetWrapperRefs,
	}
}

func transformUnionTypeRefs(source, target *expr.AttributeExpr, ta *transformAttrs, src, tgt *expr.Union) ([]string, []string) {
	sourceValueTypeRefs := make([]string, len(src.Values))
	targetWrapperRefs := make([]string, len(src.Values))
	if ta.proto {
		buildProtoUnionTypeRefs(source, ta, src, sourceValueTypeRefs)
		return sourceValueTypeRefs, targetWrapperRefs
	}
	buildSourceUnionTypeRefs(ta, src, sourceValueTypeRefs)
	buildTargetUnionWrapperRefs(target, ta, tgt, targetWrapperRefs)
	return sourceValueTypeRefs, targetWrapperRefs
}

func buildProtoUnionTypeRefs(source *expr.AttributeExpr, ta *transformAttrs, src *expr.Union, sourceValueTypeRefs []string) {
	unionPkg := ta.SourceCtx.Pkg(source)
	samePkg, commonPkg := unionCommonPkg(src.Values)
	for i, v := range src.Values {
		if _, ok := v.Attribute.Type.(expr.UserType); ok {
			sourceValueTypeRefs[i] = ta.SourceCtx.Scope.Ref(v.Attribute, ta.SourceCtx.Pkg(v.Attribute))
			continue
		}
		w := codegen.Goify(src.Name(), true) + codegen.Goify(v.Name, true)
		pkg := unionPkg
		if samePkg && commonPkg != "" {
			pkg = commonPkg
		}
		if pkg != "" {
			sourceValueTypeRefs[i] = pkg + "." + w
		} else {
			sourceValueTypeRefs[i] = w
		}
	}
}

func buildSourceUnionTypeRefs(ta *transformAttrs, src *expr.Union, sourceValueTypeRefs []string) {
	for i, v := range src.Values {
		fieldName := ta.SourceCtx.Scope.Field(v.Attribute, v.Name, true)
		sourceValueTypeRefs[i] = ta.message + "_" + fieldName
	}
}

func buildTargetUnionWrapperRefs(target *expr.AttributeExpr, ta *transformAttrs, tgt *expr.Union, targetWrapperRefs []string) {
	unionPkg := ta.TargetCtx.Pkg(target)
	samePkg, commonPkg := unionCommonPkg(tgt.Values)
	for i, tv := range tgt.Values {
		if _, ok := tv.Attribute.Type.(expr.UserType); ok {
			continue
		}
		w := codegen.Goify(tgt.Name(), true) + codegen.Goify(tv.Name, true)
		pkg := unionPkg
		if samePkg && commonPkg != "" {
			pkg = commonPkg
		}
		if pkg != "" {
			targetWrapperRefs[i] = pkg + "." + w
		} else {
			targetWrapperRefs[i] = w
		}
	}
}

func unionCommonPkg(values []*expr.NamedAttributeExpr) (bool, string) {
	samePkg := true
	commonPkg := ""
	for _, v := range values {
		ut, ok := v.Attribute.Type.(expr.UserType)
		if !ok {
			return false, ""
		}
		loc := codegen.UserTypeLocation(ut)
		if loc == nil {
			return false, ""
		}
		if commonPkg == "" {
			commonPkg = loc.PackageName()
			continue
		}
		if commonPkg != loc.PackageName() {
			return false, ""
		}
	}
	return samePkg, commonPkg
}

// transformAttributeHelpers returns the Go transform functions and their definitions
// that may be used in code produced by Transform. It returns an error if source and
// target are incompatible (different types, fields of different type etc).
//
// source, target are the source and target attributes used in transformation
//
// ta is the transform attributes
//
// seen keeps track of generated transform functions to avoid recursion
func transformAttributeHelpers(source, target *expr.AttributeExpr, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) ([]*codegen.TransformFunctionData, error) {
	var (
		helpers []*codegen.TransformFunctionData
		err     error
	)
	{
		if err = codegen.IsCompatible(source.Type, target.Type, "", ""); err != nil {
			if ta.proto {
				target = unwrapAttr(expr.DupAtt(target))
			} else {
				source = unwrapAttr(expr.DupAtt(source))
			}
			if err = codegen.IsCompatible(source.Type, target.Type, "", ""); err != nil {
				return nil, err
			}
		}
		// Do not generate a transform function for the top most user type.
		switch {
		case expr.IsArray(source.Type):
			source = expr.AsArray(source.Type).ElemType
			target = expr.AsArray(target.Type).ElemType
			helpers, err = transformAttributeHelpers(source, target, ta, seen)
		case expr.IsMap(source.Type):
			sm := expr.AsMap(source.Type)
			tm := expr.AsMap(target.Type)
			helpers, err = transformAttributeHelpers(sm.ElemType, tm.ElemType, ta, seen)
			if err == nil {
				var other []*codegen.TransformFunctionData
				other, err = transformAttributeHelpers(sm.KeyType, tm.KeyType, ta, seen)
				helpers = append(helpers, other...)
			}
		case expr.IsUnion(source.Type):
			srcAttrs := expr.AsUnion(source.Type)
			tgtAttrs := expr.AsUnion(target.Type)
			if len(srcAttrs.Values) != len(tgtAttrs.Values) {
				return nil, fmt.Errorf("cannot transform union attribute %s with %d types to union attribute %s with %d types",
					source.Type.Name(), len(srcAttrs.Values), target.Type.Name(), len(tgtAttrs.Values))
			}
			for i, srcAtt := range srcAttrs.Values {
				tgtAtt := tgtAttrs.Values[i]
				h, err := collectHelpers(srcAtt.Attribute, tgtAtt.Attribute, true, ta, seen)
				if err == nil {
					helpers = append(helpers, h...)
				}
			}
		case expr.IsObject(source.Type):
			walkMatches(source, target, func(srcMatt, _ *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string) {
				if err != nil {
					return
				}
				if err = codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err != nil {
					if ta.proto {
						tgtc = unwrapAttr(tgtc)
					} else {
						srcc = unwrapAttr(srcc)
					}
					if err = codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err != nil {
						return
					}
				}
				h, err2 := collectHelpers(srcc, tgtc, srcMatt.IsRequired(n), ta, seen)
				if err2 != nil {
					err = err2
					return
				}
				helpers = append(helpers, h...)
			})
		}
	}
	if err != nil {
		return nil, err
	}
	return helpers, nil
}

// collectHelpers recursively traverses the given attributes and return the
// transform helper functions required to generate the transform code.
func collectHelpers(source, target *expr.AttributeExpr, req bool, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) ([]*codegen.TransformFunctionData, error) {
	switch {
	case expr.IsArray(source.Type):
		return transformAttributeHelpers(expr.AsArray(source.Type).ElemType, expr.AsArray(target.Type).ElemType, ta, seen)
	case expr.IsMap(source.Type):
		return collectMapHelpers(source, target, ta, seen)
	case expr.IsUnion(source.Type):
		return collectUnionHelpers(source, target, ta, seen)
	case expr.IsObject(source.Type):
		return collectObjectHelpers(source, target, req, ta, seen)
	}
	return nil, nil
}

func collectMapHelpers(source, target *expr.AttributeExpr, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) ([]*codegen.TransformFunctionData, error) {
	data, err := transformAttributeHelpers(expr.AsMap(source.Type).KeyType, expr.AsMap(target.Type).KeyType, ta, seen)
	if err != nil {
		return nil, err
	}
	helpers, err := transformAttributeHelpers(expr.AsMap(source.Type).ElemType, expr.AsMap(target.Type).ElemType, ta, seen)
	if err != nil {
		return nil, err
	}
	return append(data, helpers...), nil
}

func collectUnionHelpers(source, target *expr.AttributeExpr, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) ([]*codegen.TransformFunctionData, error) {
	srcAttrs := expr.AsUnion(source.Type)
	tgtAttrs := expr.AsUnion(target.Type)
	if len(srcAttrs.Values) != len(tgtAttrs.Values) {
		return nil, fmt.Errorf("cannot transform union attribute %s with %d types to union attribute %s with %d types", source.Type.Name(), len(srcAttrs.Values), target.Type.Name(), len(tgtAttrs.Values))
	}
	var data []*codegen.TransformFunctionData
	for i, srcVal := range srcAttrs.Values {
		src := srcVal.Attribute
		tgt := tgtAttrs.Values[i].Attribute
		if ta.proto {
			tgt = unwrapAttr(tgt)
		} else {
			src = unwrapAttr(src)
		}
		helpers, err := collectHelpers(src, tgt, true, ta, seen)
		if err != nil {
			return nil, err
		}
		data = append(data, helpers...)
	}
	return data, nil
}

func collectObjectHelpers(source, target *expr.AttributeExpr, req bool, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) ([]*codegen.TransformFunctionData, error) {
	var data []*codegen.TransformFunctionData
	if ut, ok := source.Type.(expr.UserType); ok {
		tfd, stop, err := buildObjectHelper(source, target, req, ut, ta, seen)
		if err != nil {
			return nil, err
		}
		if stop {
			return nil, nil
		}
		if tfd != nil {
			data = append(data, tfd)
		}
	}
	helpers, err := collectObjectFieldHelpers(source, target, ta, seen)
	if err != nil {
		return nil, err
	}
	return append(data, helpers...), nil
}

func buildObjectHelper(source, target *expr.AttributeExpr, req bool, ut expr.UserType, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) (*codegen.TransformFunctionData, bool, error) {
	ta = objectHelperTransformAttrs(source, target, ta)
	name := transformHelperName(source, target, ta)
	if _, ok := seen[name]; ok {
		return nil, true, nil
	}
	code, err := transformAttribute(ut.Attribute(), target, "v", "res", true, ta)
	if err != nil {
		return nil, false, err
	}
	if !req {
		code = "if v == nil {\n\treturn nil\n}\n" + code
	}
	tfd := &codegen.TransformFunctionData{
		Name:          name,
		ParamTypeRef:  ta.SourceCtx.Scope.Ref(source, ta.SourceCtx.Pkg(source)),
		ResultTypeRef: ta.TargetCtx.Scope.Ref(target, ta.TargetCtx.Pkg(target)),
		Code:          code,
	}
	seen[name] = tfd
	return tfd, false, nil
}

func objectHelperTransformAttrs(source, target *expr.AttributeExpr, ta *transformAttrs) *transformAttrs {
	if ta.proto && isUnionMessage(target) {
		dup := dupTransformAttrs(ta)
		dup.message = dup.TargetCtx.Scope.Name(target, dup.TargetCtx.Pkg(target), false, false)
		return dup
	}
	if !ta.proto && isUnionMessage(source) {
		dup := dupTransformAttrs(ta)
		dup.message = dup.SourceCtx.Scope.Ref(source, dup.SourceCtx.Pkg(source))
		return dup
	}
	return ta
}

func collectObjectFieldHelpers(source, target *expr.AttributeExpr, ta *transformAttrs, seen map[string]*codegen.TransformFunctionData) ([]*codegen.TransformFunctionData, error) {
	var (
		data []*codegen.TransformFunctionData
		err  error
	)
	walkMatches(source, target, func(srcMatt, _ *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string) {
		if err != nil {
			return
		}
		srcc, tgtc, err = normalizedTransformAttrs(srcc, tgtc, ta)
		if err != nil {
			return
		}
		var helpers []*codegen.TransformFunctionData
		helpers, err = collectHelpers(srcc, tgtc, srcMatt.IsRequired(n), ta, seen)
		if err != nil {
			return
		}
		data = append(data, helpers...)
	})
	if err != nil {
		return nil, err
	}
	return data, nil
}

func normalizedTransformAttrs(srcc, tgtc *expr.AttributeExpr, ta *transformAttrs) (*expr.AttributeExpr, *expr.AttributeExpr, error) {
	if err := codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err == nil {
		return srcc, tgtc, nil
	}
	if ta.proto {
		tgtc = unwrapAttr(tgtc)
	} else {
		srcc = unwrapAttr(srcc)
	}
	if err := codegen.IsCompatible(srcc.Type, tgtc.Type, "", ""); err != nil {
		return nil, nil, err
	}
	return srcc, tgtc, nil
}

// walkMatches iterates through the source attribute expression and executes
// the walker function.
func walkMatches(source, target *expr.AttributeExpr, walker func(src, tgt *expr.MappedAttributeExpr, srcc, tgtc *expr.AttributeExpr, n string)) {
	srcMatt := expr.NewMappedAttributeExpr(source)
	tgtMatt := expr.NewMappedAttributeExpr(target)
	srcObj := expr.AsObject(srcMatt.Type)
	tgtObj := expr.AsObject(tgtMatt.Type)
	for _, nat := range *srcObj {
		if att := tgtObj.Attribute(nat.Name); att != nil {
			walker(srcMatt, tgtMatt, nat.Attribute, att, nat.Name)
		}
	}
}

// transformHelperName returns the transformation function name to initialize a
// target user type from an instance of a source user type.
func transformHelperName(source, target *expr.AttributeExpr, ta *transformAttrs) string {
	var (
		sname  string
		tname  string
		prefix string
	)
	{
		// Do not consider package overrides for protogen generated types
		if ta.proto {
			target = expr.DupAtt(target)
			codegen.Walk(target, func(att *expr.AttributeExpr) error { // nolint: errcheck
				delete(att.Meta, "struct:pkg:path")
				return nil
			})
		} else {
			source = expr.DupAtt(source)
			codegen.Walk(source, func(att *expr.AttributeExpr) error { // nolint: errcheck
				delete(att.Meta, "struct:pkg:path")
				return nil
			})
		}
		sname = codegen.Goify(ta.SourceCtx.Scope.Name(source, ta.SourceCtx.Pkg(source), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault), true)
		tname = codegen.Goify(ta.TargetCtx.Scope.Name(target, ta.TargetCtx.Pkg(target), ta.TargetCtx.Pointer, ta.TargetCtx.UseDefault), true)
		prefix = ta.Prefix
	}
	return codegen.Goify(prefix+sname+"To"+tname, false)
}

// unAlias returns the base AttributeExpr of an aliased one.
func unAlias(at *expr.AttributeExpr) *expr.AttributeExpr {
	if prim := getPrimitive(at); prim != nil {
		return prim
	}
	return at
}

// isUnionMessage returns true if the given attribute is a union message.
func isUnionMessage(at *expr.AttributeExpr) bool {
	ut, ok := at.Type.(expr.UserType)
	if !ok {
		return false
	}
	obj := expr.AsObject(ut.Attribute().Type)
	if obj == nil {
		return false
	}
	for _, nat := range *obj {
		if expr.IsUnion(nat.Attribute.Type) {
			return true
		}
	}
	return false
}

// dupTransformAttrs returns a shallow copy of the given transformAttrs.
func dupTransformAttrs(ta *transformAttrs) *transformAttrs {
	return &transformAttrs{
		TransformAttrs: ta.TransformAttrs,
		proto:          ta.proto,
		targetInit:     ta.targetInit,
		wrapped:        ta.wrapped,
		message:        ta.message,
	}
}
