package codegen

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/CaliLuke/loom/expr"

	"github.com/CaliLuke/loom/codegen"
)

type (
	// protoBufScope is the scope for protocol buffer attribute types.
	protoBufScope struct {
		scope *codegen.NameScope
	}
)

// Name returns the protocol buffer type name.
func (p *protoBufScope) Name(att *expr.AttributeExpr, pkg string, _, _ bool) string {
	return protoBufGoFullTypeName(att, pkg, p.scope)
}

// Ref returns the protocol buffer type reference.
func (p *protoBufScope) Ref(att *expr.AttributeExpr, pkg string) string {
	return protoBufGoFullTypeRef(att, pkg, p.scope)
}

// Field returns the field name as generated by protocol buffer compiler.
// NOTE: protoc does not care about common initialisms like api -> API so we
// first transform the name into snake case to end up with Api.
func (*protoBufScope) Field(att *expr.AttributeExpr, name string, firstUpper bool) string {
	return protoBufifyAtt(att, codegen.SnakeCase(name), firstUpper)
}

// UnionFieldNames returns the name of the Go field of the oneof that holds
// the union field name of the message with the object attribute obj, and the
// names of the Go fields of its oneof fields in branch order. The fields,
// oneofs and oneof fields of a message share one namespace, so these names
// depend on the other fields of the message, see newProtoMessageNames.
func (*protoBufScope) UnionFieldNames(obj *expr.AttributeExpr, name string) (string, []string) {
	names := newProtoMessageNames(expr.AsObject(obj.Type))
	return names.goField(name), names.goBranches(name)
}

// Scope returns the name scope.
func (p *protoBufScope) Scope() *codegen.NameScope {
	return p.scope
}

// protoBufTypeContext returns a contextual attribute for the protocol buffer type.
func protoBufTypeContext(pkg string, scope *codegen.NameScope, useDefault bool) *codegen.AttributeContext {
	ctx := codegen.NewAttributeContext(false, true, useDefault, pkg, scope)
	ctx.Scope = &protoBufScope{scope: scope}
	return ctx
}

// makeProtoBufMessage ensures the resulting attribute is an object user type so
// that it can be directly mapped to a protobuf type (protobuf messages must
// always be objects). If the given attribute type is a primitive, array, map
// or union, it wraps the given attribute with an object with a single "field"
// attribute. A wrapped union is required and generates a message with a oneof
// that unionWrapperFieldName names and whose branches are numbered from 1. For nested arrays/maps,
// the inner array/map is wrapped into a user type.
func makeProtoBufMessage(att *expr.AttributeExpr, tname string, sd *ServiceData) *expr.AttributeExpr {
	att = expr.DupAtt(att)
	expr.RemovePkgPath(att)
	ut, isut := att.Type.(expr.UserType)
	switch {
	case att.Type == expr.Empty:
		att.Type = &expr.UserTypeExpr{
			TypeName:      tname,
			AttributeExpr: &expr.AttributeExpr{Type: &expr.Object{}},
			UID:           sd.Name + "#" + tname,
		}
		return att
	case expr.IsPrimitive(att.Type):
		wrapAttr(att, tname, true, sd)
		return att
	case isut:
		switch {
		case expr.IsArray(ut):
			// A named array payload or result is the same message as the
			// named array anywhere else, including references to it from
			// its own elements when it is recursive.
			wrapArrayUserType(att)
			att.Validation = nil
		case expr.IsUnion(ut):
			wrapAttr(att, tname, true, sd)
		}
	case expr.IsArray(att.Type) || expr.IsMap(att.Type):
		wrapAttr(att, tname, false, sd)
	case expr.IsUnion(att.Type):
		wrapAttr(att, tname, true, sd)
	case expr.IsObject(att.Type):
		att.Type = &expr.UserTypeExpr{
			TypeName:      tname,
			AttributeExpr: expr.DupAtt(att),
			UID:           sd.Name + "#" + tname,
		}
	}
	n := ""
	makeProtoBufMessageR(att, &n, sd, make(map[string]struct{}), messageScope{})
	return att
}

// makeProtoBufMessageR is the recursive implementation of makeProtoBufMessage.
// scope identifies the position of att in the enclosing message and names the
// messages generated for anonymous objects nested in att.
func makeProtoBufMessageR(att *expr.AttributeExpr, tname *string, sd *ServiceData, seen map[string]struct{}, scope messageScope) {
	wrapArrayUserType(att)
	ut, isut := att.Type.(expr.UserType)

	// handle infinite recursions
	if isut {
		if _, ok := seen[ut.ID()]; ok {
			return
		}
		seen[ut.ID()] = struct{}{}
	}

	wrap := func(att *expr.AttributeExpr, tname string) {
		switch {
		case expr.IsArray(att.Type):
			wrapAttr(att, "ArrayOf"+tname+
				protoBufify(protoBufMessageDef(expr.AsArray(att.Type).ElemType, sd), true, true), true, sd)
		case expr.IsMap(att.Type):
			m := expr.AsMap(att.Type)
			wrapAttr(att, tname+"MapOf"+
				protoBufify(protoBufMessageDef(m.KeyType, sd), true, true)+
				protoBufify(protoBufMessageDef(m.ElemType, sd), true, true), true, sd)
		}
	}

	switch {
	case expr.IsPrimitive(att.Type):
		return
	case isut:
		makeProtoBufMessageR(ut.Attribute(), tname, sd, seen, messageScope{name: ut.Name(), path: strconv.Quote(ut.Name())})
	case expr.IsArray(att.Type):
		ar := expr.AsArray(att.Type)
		scope.path += "/[]"
		nameAnonymousMessage(ar.ElemType, scope, sd)
		makeProtoBufMessageR(ar.ElemType, tname, sd, seen, scope)
		wrap(ar.ElemType, *tname)
	case expr.IsMap(att.Type):
		m := expr.AsMap(att.Type)
		scope.path += "/{}"
		nameAnonymousMessage(m.ElemType, scope, sd)
		makeProtoBufMessageR(m.ElemType, tname, sd, seen, scope)
		wrap(m.ElemType, *tname)
	case expr.IsUnion(att.Type):
		for _, nat := range expr.AsUnion(att.Type).Values {
			wrapUnionBranch(nat.Attribute, sd)
			makeProtoBufMessageField(nat, tname, sd, seen, scope)
		}
	case expr.IsObject(att.Type):
		for _, nat := range *(expr.AsObject(att.Type)) {
			makeProtoBufMessageField(nat, tname, sd, seen, scope)
		}
	}
}

// protoBufMessageName returns the protocol buffer message name of the given
// attribute type.
func protoBufMessageName(att *expr.AttributeExpr, s *codegen.NameScope) string {
	return protoBufFullMessageName(att, "", s)
}

// protoBufFullMessageName returns the protocol buffer message name of the
// given user type qualified with the given package name if applicable.
func protoBufFullMessageName(att *expr.AttributeExpr, pkg string, s *codegen.NameScope) string {
	switch actual := att.Type.(type) {
	case expr.UserType, *expr.Union:
		n := s.HashedUnique(actual, protoBufify(actual.Name(), true, true), "")
		if name, ok := protoMetaName(att.Meta); ok {
			n = name
		}
		if pkg == "" {
			return n
		}
		return pkg + "." + n
	case expr.CompositeExpr:
		return protoBufFullMessageName(actual.Attribute(), pkg, s)
	default:
		panic(codegen.NewError(nil, att, fmt.Errorf("data type is not a user type or union: received type %T", actual)))
	}
}

// protoBufGoTypeName returns the protocol buffer type name for the given
// attribute generated after compiling the proto file (in *.pb.go).
func protoBufGoTypeName(att *expr.AttributeExpr, s *codegen.NameScope) string {
	return protoBufGoFullTypeName(att, "", s)
}

// protoBufGoFullTypeName returns the protocol buffer type name qualified with
// the given package name for the given attribute generated after compiling
// the proto file (in *.pb.go).
func protoBufGoFullTypeName(att *expr.AttributeExpr, pkg string, s *codegen.NameScope) string {
	if proto := att.Meta["struct:field:proto"]; len(proto) > 2 {
		typ := proto[2]
		if len(att.Meta["struct:field:proto"]) > 3 {
			elems := strings.Split(att.Meta["struct:field:proto"][3], "/")
			typ = elems[len(elems)-1] + "." + typ
		}
		return typ
	}
	switch actual := att.Type.(type) {
	case expr.UserType, expr.CompositeExpr, *expr.Union:
		return protoBufFullMessageName(att, pkg, s)
	case expr.Primitive:
		return protoBufNativeGoTypeName(att.Type)
	case *expr.Array:
		return "[]" + protoBufGoFullTypeRef(actual.ElemType, pkg, s)
	case *expr.Map:
		return fmt.Sprintf("map[%s]%s",
			protoBufGoFullTypeRef(actual.KeyType, pkg, s),
			protoBufGoFullTypeRef(actual.ElemType, pkg, s))
	case *expr.Object:
		return s.GoTypeDef(att, false, false)
	default:
		panic(codegen.NewError(nil, att, fmt.Errorf("unknown protocol buffer Go type %T", actual)))
	}
}

// protoType returns the protocol buffer type name for the given attribute.
func protoType(att *expr.AttributeExpr, sd *ServiceData) string {
	if protos := att.Meta["struct:field:proto"]; len(protos) > 0 {
		return protos[0]
	}
	return protoBufMessageDef(att, sd)
}

// protoBufMessageDef returns the protocol buffer code that defines a message
// which matches the data structure definition (the part that comes after
// `message foo`). The message is defined using the proto3 syntax.
func protoBufMessageDef(att *expr.AttributeExpr, sd *ServiceData) string {
	switch actual := att.Type.(type) {
	case expr.Primitive:
		return protoNativeType(att.Type)
	case *expr.Array:
		return "repeated " + protoType(actual.ElemType, sd)
	case *expr.Map:
		return fmt.Sprintf("map<%s, %s>", protoType(actual.KeyType, sd), protoType(actual.ElemType, sd))
	case *expr.Union:
		return protoBufUnionMessageDef(actual, sd)
	case expr.UserType:
		if actual == expr.Empty {
			return " {}"
		}
		if prim := getPrimitive(att); prim != nil {
			return protoBufMessageDef(prim, sd)
		}
		return protoBufMessageName(att, sd.Scope)
	case *expr.Object:
		return protoBufObjectMessageDef(att, actual, sd)
	default:
		panic(codegen.NewError(nil, att, fmt.Errorf("unknown protocol buffer message type %T", actual)))
	}
}

// protoBufUnionMessageDef returns the definition of the oneof that holds the
// branches of the union actual in a message of its own, named after the union.
func protoBufUnionMessageDef(actual *expr.Union, sd *ServiceData) string {
	name := actual.Name()
	att := &expr.AttributeExpr{Type: actual}
	names := newProtoMessageNames(&expr.Object{{Name: name, Attribute: att}})
	return protoBufOneofDef(names.field(name), names.oneofFields(name), att, sd)
}

// protoBufOneofDef returns the definition of the oneof oneofName that holds
// the branches of the union attribute att in fields named fieldNames. The
// branches take the field numbers that UnionFieldTags returns, so a union
// passed to Field numbers its branches from the field number.
func protoBufOneofDef(oneofName string, fieldNames []string, att *expr.AttributeExpr, sd *ServiceData) string {
	union := expr.AsUnion(att.Type)
	tags := att.UnionFieldTags()
	def := "\toneof " + oneofName + " {"
	for i, nat := range union.Values {
		def += fmt.Sprintf("\n\t\t%s", protoBufUnionFieldDef(nat, fieldNames[i], parseRPCTag(tags[i], nat.Attribute), sd))
	}
	return def + "\n\t}"
}

func protoBufUnionFieldDef(nat *expr.NamedAttributeExpr, fieldName string, fnum uint64, sd *ServiceData) string {
	typ := protoTypeForAttribute(nat.Attribute, sd)
	desc := protoCommentPrefix(nat.Attribute.Description)
	opt := protoJSONOption(nat.Attribute)
	return fmt.Sprintf("%s%s %s = %d%s;", desc, typ, fieldName, fnum, opt)
}

func protoBufObjectMessageDef(att *expr.AttributeExpr, actual *expr.Object, sd *ServiceData) string {
	lines := make([]string, 0, 1+len(*actual)+1)
	lines = append(lines, " {")
	names := newProtoMessageNames(actual)
	for _, nat := range *actual {
		lines = append(lines, protoBufObjectFieldLine(att, nat, names, sd))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

// protoBufObjectFieldLine returns the definition of the field nat of the
// message with the object attribute att, whose fields, oneofs and oneof fields
// take the names in names. A union field, constructor or named, is a oneof of
// the message.
func protoBufObjectFieldLine(att *expr.AttributeExpr, nat *expr.NamedAttributeExpr, names *protoMessageNames, sd *ServiceData) string {
	if expr.IsUnion(nat.Attribute.Type) {
		return protoBufOneofDef(names.field(nat.Name), names.oneofFields(nat.Name), nat.Attribute, sd)
	}
	field := protoBufObjectField(att, nat, sd)
	return fmt.Sprintf("\t%s%s%s %s = %d%s;", field.Description, field.Optional, field.TypeName, field.Name, field.Number, field.JSONOption)
}

type protoBufFieldData struct {
	Name        string
	Number      uint64
	TypeName    string
	Optional    string
	Description string
	JSONOption  string
}

func protoBufObjectField(att *expr.AttributeExpr, nat *expr.NamedAttributeExpr, sd *ServiceData) protoBufFieldData {
	return protoBufFieldData{
		Name:        codegen.SnakeCase(protoBufify(nat.Name, false, false)),
		Number:      rpcTag(nat.Attribute),
		TypeName:    protoTypeForAttribute(nat.Attribute, sd),
		Optional:    protoBufOptionalField(att, nat),
		Description: protoCommentPrefix(nat.Attribute.Description),
		JSONOption:  protoJSONOption(nat.Attribute),
	}
}

func protoTypeForAttribute(att *expr.AttributeExpr, sd *ServiceData) string {
	if prim := getPrimitive(att); prim != nil {
		return protoType(prim, sd)
	}
	return protoType(att, sd)
}

func protoBufOptionalField(att *expr.AttributeExpr, nat *expr.NamedAttributeExpr) string {
	if att.IsRequired(nat.Name) || !expr.IsPrimitive(nat.Attribute.Type) {
		return ""
	}
	return "optional "
}

func protoCommentPrefix(desc string) string {
	if desc == "" {
		return ""
	}
	return codegen.Comment(desc) + "\n\t"
}

func protoJSONOption(att *expr.AttributeExpr) string {
	if att == nil || att.Meta == nil {
		return ""
	}
	if names := att.Meta["proto:tag:json"]; len(names) > 0 && names[0] != "" {
		return fmt.Sprintf(" [json_name = %q]", names[0])
	}
	return ""
}

// protoBufGoFullTypeRef returns the Go code qualified with package name that
// refers to the Go type generated by compiling the protocol buffer
// (in *.pb.go) for the given attribute.
func protoBufGoFullTypeRef(att *expr.AttributeExpr, pkg string, s *codegen.NameScope) string {
	name := protoBufGoFullTypeName(att, pkg, s)
	if expr.IsObject(att.Type) || expr.IsUnion(att.Type) {
		return "*" + name
	}
	return name
}

// protoNativeType returns the protocol buffer built-in type
// corresponding to the given primitive type. It panics if t is not a
// primitive type.
func protoNativeType(t expr.DataType) string {
	switch t.Kind() {
	case expr.BooleanKind:
		return "bool"
	case expr.IntKind:
		return "sint64"
	case expr.Int32Kind:
		return "sint32"
	case expr.Int64Kind:
		return "sint64"
	case expr.UIntKind:
		return "uint64"
	case expr.UInt32Kind:
		return "uint32"
	case expr.UInt64Kind:
		return "uint64"
	case expr.Float32Kind:
		return "float"
	case expr.Float64Kind:
		return "double"
	case expr.StringKind:
		return "string"
	case expr.BytesKind:
		return "bytes"
	case expr.AnyKind:
		return "google.protobuf.Value"
	default:
		panic(fmt.Sprintf("cannot compute native protocol buffer type for %T", t)) // bug
	}
}

// protoBufNativeGoTypeName returns the Go type corresponding to the given
// primitive type generated by the protocol buffer compiler after compiling
// the ".proto" file (in *.pb.go).
func protoBufNativeGoTypeName(t expr.DataType) string {
	switch t.Kind() {
	case expr.BooleanKind:
		return "bool"
	case expr.IntKind:
		return "int64"
	case expr.Int32Kind:
		return "int32"
	case expr.Int64Kind:
		return "int64"
	case expr.UIntKind:
		return "uint64"
	case expr.UInt32Kind:
		return "uint32"
	case expr.UInt64Kind:
		return "uint64"
	case expr.Float32Kind:
		return "float32"
	case expr.Float64Kind:
		return "float64"
	case expr.StringKind:
		return "string"
	case expr.BytesKind:
		return "[]byte"
	case expr.AnyKind:
		return "*structpb.Value"
	default:
		panic(fmt.Sprintf("cannot compute native protocol buffer type for %T %v", t, t)) // bug
	}
}

// rpcTag returns the unique numbered RPC tag from the given attribute.
func rpcTag(a *expr.AttributeExpr) uint64 {
	t, _ := a.FieldTag()
	return parseRPCTag(t, a)
}

// parseRPCTag returns the field number tag of attribute a. It returns 0 when
// tag is empty.
func parseRPCTag(tag string, a *expr.AttributeExpr) uint64 {
	if tag == "" {
		return 0
	}
	tn, err := strconv.ParseUint(tag, 10, 64)
	if err != nil {
		panic(codegen.NewError(nil, a, fmt.Errorf("invalid protocol buffer field tag %q: %w", tag, err)))
	}
	return tn
}
