package codegen

import (
	"fmt"

	"github.com/CaliLuke/loom/codegen/service"
	"github.com/CaliLuke/loom/expr"
	"github.com/CaliLuke/loom/grpc/codegen/internal/transportir"
)

// usesStreamEnvelope reports whether the transport needs a typed stream
// envelope to carry both the one-shot method payload and streaming payload
// items through the same gRPC streamed message.
func usesStreamEnvelope(endpoint *transportir.Endpoint) bool {
	if !endpoint.Stream.IsPayloadStreaming {
		return false
	}
	return !isEmpty(endpoint.Request.Message.Type)
}

// makeProtoBufStreamEnvelope builds the protobuf stream envelope that carries
// the initial request payload frame and subsequent stream item frames.
func makeProtoBufStreamEnvelope(request, stream *expr.AttributeExpr, tname string, sd *ServiceData) *expr.AttributeExpr {
	initial := expr.DupAtt(request)
	initial.Meta = initial.Meta.Dup()
	initial.Meta["rpc:tag"] = []string{"1"}
	streamItem := expr.DupAtt(stream)
	streamItem.Meta = streamItem.Meta.Dup()
	streamItem.Meta["rpc:tag"] = []string{"2"}
	envelope := &expr.AttributeExpr{
		Type: &expr.Object{
			&expr.NamedAttributeExpr{
				Name: "body",
				Attribute: &expr.AttributeExpr{
					Type: &expr.Union{
						TypeName: "body",
						Values: []*expr.NamedAttributeExpr{
							{Name: "initial_payload", Attribute: initial},
							{Name: "stream_item", Attribute: streamItem},
						},
					},
				},
			},
		},
		Validation: &expr.ValidationExpr{Required: []string{"body"}},
	}
	return makeProtoBufMessage(envelope, tname, sd)
}

// buildStreamEnvelopeData computes the generated Go names for the protobuf
// oneof field and wrapper types of the synthesized stream envelope.
func buildStreamEnvelopeData(envelope *expr.AttributeExpr, message *service.UserTypeData, sd *ServiceData) *StreamEnvelopeData {
	names := newProtoMessageNames(expr.AsObject(envelope.Type))
	fieldName := names.goField("body")
	branches := names.goBranches("body")
	initialFieldName, streamItemFieldName := branches[0], branches[1]
	// Protobuf synthesizes wrapper types for oneof branches (e.g.
	// Message_InitialPayload). These types are generated by protoc and have
	// no AttributeExpr counterpart in the loom name scope, so a manual
	// package-qualified reference is required.
	return &StreamEnvelopeData{
		FieldName:            fieldName,
		InitialFieldName:     initialFieldName,
		InitialWrapperRef:    fmt.Sprintf("%s.%s_%s", sd.PkgName, message.VarName, initialFieldName), // nolint: namescope
		StreamItemFieldName:  streamItemFieldName,
		StreamItemWrapperRef: fmt.Sprintf("%s.%s_%s", sd.PkgName, message.VarName, streamItemFieldName), // nolint: namescope
	}
}
