package scripts_test

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestHandWrittenGoSources(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("source discovery is used by the Unix formatting and lint gates")
	}
	script, err := filepath.Abs("go_sources.sh")
	require.NoError(t, err)
	for _, tc := range []struct {
		name      string
		files     map[string]string
		find      string
		want      []string
		wantError string
	}{
		{
			name: "selection",
			files: map[string]string{
				"hand.go":             "package p\n",
				"bom.go":              "\ufeffpackage p\nconst source = `\n// Code generated by tool. DO NOT EDIT.\n`\n",
				"block_comment.go":    "/*\n// Code generated by tool. DO NOT EDIT.\n*/\npackage p\n",
				"indented_package.go": " \tpackage p\nconst source = `\n// Code generated by tool. DO NOT EDIT.\n`\n",
				"with space.go":       "package p\n",
				"testdata/dsl.go":     "package testdata\n",
				"generated.go":        "// license\n// Code generated by tool. DO NOT EDIT.\npackage p\n",
				"crlf.go":             "// Code generated by tool. DO NOT EDIT.\r\npackage p\r\n",
				"literal_test.go":     "package p\nconst source = `\n// Code generated by tool. DO NOT EDIT.\npackage generated\n`\n",
				"manual_marker.go":    "// Code generated by tool but edited manually\npackage p\n",
				"gen/hidden.go":       "package p\n",
				"http/integration_tests/fixtures/app/hidden.go": "package p\n",
				"http/integration_tests/tests/test.go":          "package p\n",
				".git/hidden.go":                                "package p\n",
				"nested/.git":                                   "gitdir: /tmp/other\n",
				"nested/hidden.go":                              "package p\n",
			},
			want: []string{"./bom.go", "./hand.go", "./http/integration_tests/tests/test.go", "./indented_package.go", "./literal_test.go", "./manual_marker.go", "./testdata/dsl.go", "./with space.go"},
		},
		{
			name:      "partial discovery failure",
			files:     map[string]string{"partial.go": "package p\n"},
			find:      "printf './partial.go\\n'\nexit 9\n",
			wantError: "Go source discovery failed",
		},
		{
			name:      "discovered file cannot be read",
			find:      "printf './missing.go\\n'\n",
			wantError: "Go source discovery failed",
		},
		{
			name:      "empty discovery",
			wantError: "Go source discovery found no hand-written Go files",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			for name, content := range tc.files {
				path := filepath.Join(dir, name)
				require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
				require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
			}
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			cmd := exec.CommandContext(ctx, "bash", "-c", `source "$1"
if load_hand_written_go_files; then
  printf '%s\n' "${GO_FILES[@]}"
else
  test "${#GO_FILES[@]}" -eq 0 || exit 2
  exit 1
fi`, "discovery-test", script)
			cmd.Dir = dir
			if tc.find != "" {
				shim := filepath.Join(dir, "bin")
				require.NoError(t, os.Mkdir(shim, 0o700))
				require.NoError(t, os.WriteFile(filepath.Join(shim, "find"), []byte("#!/bin/sh\n"+tc.find), 0o700))
				cmd.Env = append(os.Environ(), "PATH="+shim+string(os.PathListSeparator)+os.Getenv("PATH"))
			}
			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr
			err := cmd.Run()
			if tc.wantError != "" {
				require.Error(t, err)
				require.NotNil(t, cmd.ProcessState)
				require.Equal(t, 1, cmd.ProcessState.ExitCode(), stderr.String())
				require.Contains(t, stderr.String(), tc.wantError)
				require.Empty(t, stdout.String(), "failed discovery must not publish partial results")
				return
			}
			require.NoError(t, err, stderr.String())
			require.Equal(t, tc.want, strings.Split(strings.TrimSpace(stdout.String()), "\n"))
		})
	}
}
