package expr

import (
	"regexp"
	"strings"

	"github.com/CaliLuke/loom/eval"
)

type (
	// HTTPExpr contains the API level HTTP specific expressions.
	HTTPExpr struct {
		// Path is the common request path prefix to all the service
		// HTTP endpoints.
		Path string
		// Params defines the HTTP request path and query parameters
		// common to all the API endpoints.
		Params *MappedAttributeExpr
		// Headers defines the HTTP request headers common to to all
		// the API endpoints.
		Headers *MappedAttributeExpr
		// Cookies defines the HTTP request cookies common to to all
		// the API endpoints.
		Cookies *MappedAttributeExpr
		// Consumes lists the mime types supported by the API
		// controllers.
		Consumes []string
		// Produces lists the mime types generated by the API
		// controllers.
		Produces []string
		// Services contains the services created by the DSL.
		Services []*HTTPServiceExpr
		// Errors lists the error HTTP responses.
		Errors []*HTTPErrorExpr
		// SSE contains the Server-Sent Events configuration for all
		// streaming endpoints in the API.
		SSE *HTTPSSEExpr
		// CORS contains the API-level Cross-Origin Resource Sharing policy.
		CORS *HTTPCORSExpr
	}
)

// HTTPWildcardRegex is the regular expression used to capture path
// parameters.
var HTTPWildcardRegex = regexp.MustCompile(`/{\*?([a-zA-Z0-9_]+)}`)

// ExtractHTTPWildcards returns the names of the wildcards that appear in
// a HTTP path.
func ExtractHTTPWildcards(path string) []string {
	matches := HTTPWildcardRegex.FindAllStringSubmatch(path, -1)
	wcs := make([]string, len(matches))
	for i, m := range matches {
		wcs[i] = m[1]
	}
	return wcs
}

// Service returns the service with the given name if any.
func (h *HTTPExpr) Service(name string) *HTTPServiceExpr {
	for _, res := range h.Services {
		if res.Name() == name {
			return res
		}
	}
	return nil
}

// ServiceFor creates a new or returns the existing service definition for the
// given service.
func (h *HTTPExpr) ServiceFor(s *ServiceExpr, root *HTTPExpr) *HTTPServiceExpr {
	if res := h.Service(s.Name); res != nil {
		return res
	}
	res := &HTTPServiceExpr{
		ServiceExpr: s,
		Root:        root,
	}
	h.Services = append(h.Services, res)
	return res
}

// EvalName returns the name printed in case of evaluation error.
func (*HTTPExpr) EvalName() string {
	return "API HTTP"
}

// Validate validates the API-level HTTP expression.
func (h *HTTPExpr) Validate() error {
	verr := new(eval.ValidationErrors)
	if h.CORS != nil {
		verr.Merge(h.CORS.Validate())
	}
	return verr
}

// Finalize initializes Consumes and Produces with defaults if not set.
func (h *HTTPExpr) Finalize() {
	if len(h.Consumes) == 0 {
		h.Consumes = []string{"application/json", "application/xml", "application/gob"}
	}
	if len(h.Produces) == 0 {
		h.Produces = []string{"application/json", "application/xml", "application/gob"}
	}
}

// validateHTTPPathWildcards checks the full request path against the parameter
// grammar shared by extraction, path generation, and routing. Parameters start
// a segment, names contain ASCII letters, digits, or underscores, and catch-alls
// terminate the path. Unmatched braces, duplicate names, and bare stars are invalid.
func validateHTTPPathWildcards(verr *eval.ValidationErrors, e eval.Expression, path string) {
	matches := HTTPWildcardRegex.FindAllStringSubmatchIndex(path, -1)
	wcs := make(map[string]struct{}, len(matches))
	var rest strings.Builder
	last := 0
	for _, match := range matches {
		name := path[match[2]:match[3]]
		if _, ok := wcs[name]; ok {
			verr.Add(e, "Wildcard %q appears multiple times in full path %q", name, path)
		}
		wcs[name] = struct{}{}
		if strings.HasPrefix(path[match[0]:], "/{*") && match[1] != len(path) {
			verr.Add(e, "Catch-all wildcard %q must terminate full path %q", name, path)
		}
		rest.WriteString(path[last:match[0]])
		last = match[1]
	}
	rest.WriteString(path[last:])
	if strings.ContainsAny(rest.String(), "{}") {
		verr.Add(e, "Path %q uses unsupported path parameter syntax; use one {name} parameter at the start of each segment, with only letters, digits, or underscores in names", path)
	}
	if strings.Contains(rest.String(), "*") {
		verr.Add(e, "Path %q uses a bare \"*\"; use a trailing \"/{*name}\" catch-all wildcard instead", path)
	}
}
